// Code generated by ent, DO NOT EDIT.

package job

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shjtmy/go_sh0jitmy_template/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldID, id))
}

// ScenarioID applies equality check predicate on the "scenario_id" field. It's identical to ScenarioIDEQ.
func ScenarioID(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldScenarioID, v))
}

// ScenarioVersion applies equality check predicate on the "scenario_version" field. It's identical to ScenarioVersionEQ.
func ScenarioVersion(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldScenarioVersion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStatus, v))
}

// TriggeredBy applies equality check predicate on the "triggered_by" field. It's identical to TriggeredByEQ.
func TriggeredBy(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTriggeredBy, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// ScenarioIDEQ applies the EQ predicate on the "scenario_id" field.
func ScenarioIDEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldScenarioID, v))
}

// ScenarioIDNEQ applies the NEQ predicate on the "scenario_id" field.
func ScenarioIDNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldScenarioID, v))
}

// ScenarioIDIn applies the In predicate on the "scenario_id" field.
func ScenarioIDIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldScenarioID, vs...))
}

// ScenarioIDNotIn applies the NotIn predicate on the "scenario_id" field.
func ScenarioIDNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldScenarioID, vs...))
}

// ScenarioIDGT applies the GT predicate on the "scenario_id" field.
func ScenarioIDGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldScenarioID, v))
}

// ScenarioIDGTE applies the GTE predicate on the "scenario_id" field.
func ScenarioIDGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldScenarioID, v))
}

// ScenarioIDLT applies the LT predicate on the "scenario_id" field.
func ScenarioIDLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldScenarioID, v))
}

// ScenarioIDLTE applies the LTE predicate on the "scenario_id" field.
func ScenarioIDLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldScenarioID, v))
}

// ScenarioIDContains applies the Contains predicate on the "scenario_id" field.
func ScenarioIDContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldScenarioID, v))
}

// ScenarioIDHasPrefix applies the HasPrefix predicate on the "scenario_id" field.
func ScenarioIDHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldScenarioID, v))
}

// ScenarioIDHasSuffix applies the HasSuffix predicate on the "scenario_id" field.
func ScenarioIDHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldScenarioID, v))
}

// ScenarioIDEqualFold applies the EqualFold predicate on the "scenario_id" field.
func ScenarioIDEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldScenarioID, v))
}

// ScenarioIDContainsFold applies the ContainsFold predicate on the "scenario_id" field.
func ScenarioIDContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldScenarioID, v))
}

// ScenarioVersionEQ applies the EQ predicate on the "scenario_version" field.
func ScenarioVersionEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldScenarioVersion, v))
}

// ScenarioVersionNEQ applies the NEQ predicate on the "scenario_version" field.
func ScenarioVersionNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldScenarioVersion, v))
}

// ScenarioVersionIn applies the In predicate on the "scenario_version" field.
func ScenarioVersionIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldScenarioVersion, vs...))
}

// ScenarioVersionNotIn applies the NotIn predicate on the "scenario_version" field.
func ScenarioVersionNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldScenarioVersion, vs...))
}

// ScenarioVersionGT applies the GT predicate on the "scenario_version" field.
func ScenarioVersionGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldScenarioVersion, v))
}

// ScenarioVersionGTE applies the GTE predicate on the "scenario_version" field.
func ScenarioVersionGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldScenarioVersion, v))
}

// ScenarioVersionLT applies the LT predicate on the "scenario_version" field.
func ScenarioVersionLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldScenarioVersion, v))
}

// ScenarioVersionLTE applies the LTE predicate on the "scenario_version" field.
func ScenarioVersionLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldScenarioVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldStatus, v))
}

// DynamicInputsIsNil applies the IsNil predicate on the "dynamic_inputs" field.
func DynamicInputsIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldDynamicInputs))
}

// DynamicInputsNotNil applies the NotNil predicate on the "dynamic_inputs" field.
func DynamicInputsNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldDynamicInputs))
}

// LockedTargetsIsNil applies the IsNil predicate on the "locked_targets" field.
func LockedTargetsIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldLockedTargets))
}

// LockedTargetsNotNil applies the NotNil predicate on the "locked_targets" field.
func LockedTargetsNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldLockedTargets))
}

// TriggeredByEQ applies the EQ predicate on the "triggered_by" field.
func TriggeredByEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTriggeredBy, v))
}

// TriggeredByNEQ applies the NEQ predicate on the "triggered_by" field.
func TriggeredByNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldTriggeredBy, v))
}

// TriggeredByIn applies the In predicate on the "triggered_by" field.
func TriggeredByIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldTriggeredBy, vs...))
}

// TriggeredByNotIn applies the NotIn predicate on the "triggered_by" field.
func TriggeredByNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldTriggeredBy, vs...))
}

// TriggeredByGT applies the GT predicate on the "triggered_by" field.
func TriggeredByGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldTriggeredBy, v))
}

// TriggeredByGTE applies the GTE predicate on the "triggered_by" field.
func TriggeredByGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldTriggeredBy, v))
}

// TriggeredByLT applies the LT predicate on the "triggered_by" field.
func TriggeredByLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldTriggeredBy, v))
}

// TriggeredByLTE applies the LTE predicate on the "triggered_by" field.
func TriggeredByLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldTriggeredBy, v))
}

// TriggeredByContains applies the Contains predicate on the "triggered_by" field.
func TriggeredByContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldTriggeredBy, v))
}

// TriggeredByHasPrefix applies the HasPrefix predicate on the "triggered_by" field.
func TriggeredByHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldTriggeredBy, v))
}

// TriggeredByHasSuffix applies the HasSuffix predicate on the "triggered_by" field.
func TriggeredByHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldTriggeredBy, v))
}

// TriggeredByIsNil applies the IsNil predicate on the "triggered_by" field.
func TriggeredByIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldTriggeredBy))
}

// TriggeredByNotNil applies the NotNil predicate on the "triggered_by" field.
func TriggeredByNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldTriggeredBy))
}

// TriggeredByEqualFold applies the EqualFold predicate on the "triggered_by" field.
func TriggeredByEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldTriggeredBy, v))
}

// TriggeredByContainsFold applies the ContainsFold predicate on the "triggered_by" field.
func TriggeredByContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldTriggeredBy, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldFinishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Job) predicate.Job {
	return predicate.Job(sql.NotPredicates(p))
}
