// Code generated by ent, DO NOT EDIT.

package scenario

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shjtmy/go_sh0jitmy_template/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Scenario {
	return predicate.Scenario(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Scenario {
	return predicate.Scenario(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Scenario {
	return predicate.Scenario(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Scenario {
	return predicate.Scenario(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Scenario {
	return predicate.Scenario(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Scenario {
	return predicate.Scenario(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Scenario {
	return predicate.Scenario(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Scenario {
	return predicate.Scenario(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Scenario {
	return predicate.Scenario(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldDescription, v))
}

// CurrentVersion applies equality check predicate on the "current_version" field. It's identical to CurrentVersionEQ.
func CurrentVersion(v int) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldCurrentVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Scenario {
	return predicate.Scenario(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Scenario {
	return predicate.Scenario(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Scenario {
	return predicate.Scenario(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Scenario {
	return predicate.Scenario(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Scenario {
	return predicate.Scenario(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Scenario {
	return predicate.Scenario(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Scenario {
	return predicate.Scenario(sql.FieldContainsFold(FieldDescription, v))
}

// CurrentVersionEQ applies the EQ predicate on the "current_version" field.
func CurrentVersionEQ(v int) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldCurrentVersion, v))
}

// CurrentVersionNEQ applies the NEQ predicate on the "current_version" field.
func CurrentVersionNEQ(v int) predicate.Scenario {
	return predicate.Scenario(sql.FieldNEQ(FieldCurrentVersion, v))
}

// CurrentVersionIn applies the In predicate on the "current_version" field.
func CurrentVersionIn(vs ...int) predicate.Scenario {
	return predicate.Scenario(sql.FieldIn(FieldCurrentVersion, vs...))
}

// CurrentVersionNotIn applies the NotIn predicate on the "current_version" field.
func CurrentVersionNotIn(vs ...int) predicate.Scenario {
	return predicate.Scenario(sql.FieldNotIn(FieldCurrentVersion, vs...))
}

// CurrentVersionGT applies the GT predicate on the "current_version" field.
func CurrentVersionGT(v int) predicate.Scenario {
	return predicate.Scenario(sql.FieldGT(FieldCurrentVersion, v))
}

// CurrentVersionGTE applies the GTE predicate on the "current_version" field.
func CurrentVersionGTE(v int) predicate.Scenario {
	return predicate.Scenario(sql.FieldGTE(FieldCurrentVersion, v))
}

// CurrentVersionLT applies the LT predicate on the "current_version" field.
func CurrentVersionLT(v int) predicate.Scenario {
	return predicate.Scenario(sql.FieldLT(FieldCurrentVersion, v))
}

// CurrentVersionLTE applies the LTE predicate on the "current_version" field.
func CurrentVersionLTE(v int) predicate.Scenario {
	return predicate.Scenario(sql.FieldLTE(FieldCurrentVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Scenario {
	return predicate.Scenario(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Scenario) predicate.Scenario {
	return predicate.Scenario(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Scenario) predicate.Scenario {
	return predicate.Scenario(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Scenario) predicate.Scenario {
	return predicate.Scenario(sql.NotPredicates(p))
}
