// Code generated by ent, DO NOT EDIT.

package credentialprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the credentialprofile type in the database.
	Label = "credential_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldSecLevel holds the string denoting the sec_level field in the database.
	FieldSecLevel = "sec_level"
	// FieldCommunity holds the string denoting the community field in the database.
	FieldCommunity = "community"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldAuthProtocol holds the string denoting the auth_protocol field in the database.
	FieldAuthProtocol = "auth_protocol"
	// FieldAuthPassphrase holds the string denoting the auth_passphrase field in the database.
	FieldAuthPassphrase = "auth_passphrase"
	// FieldPrivProtocol holds the string denoting the priv_protocol field in the database.
	FieldPrivProtocol = "priv_protocol"
	// FieldPrivPassphrase holds the string denoting the priv_passphrase field in the database.
	FieldPrivPassphrase = "priv_passphrase"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the credentialprofile in the database.
	Table = "credential_profiles"
)

// Columns holds all SQL columns for credentialprofile fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldVersion,
	FieldSecLevel,
	FieldCommunity,
	FieldUsername,
	FieldAuthProtocol,
	FieldAuthPassphrase,
	FieldPrivProtocol,
	FieldPrivPassphrase,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion string
	// DefaultSecLevel holds the default value on creation for the "sec_level" field.
	DefaultSecLevel string
	// DefaultCommunity holds the default value on creation for the "community" field.
	DefaultCommunity string
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// DefaultAuthProtocol holds the default value on creation for the "auth_protocol" field.
	DefaultAuthProtocol string
	// DefaultAuthPassphrase holds the default value on creation for the "auth_passphrase" field.
	DefaultAuthPassphrase string
	// DefaultPrivProtocol holds the default value on creation for the "priv_protocol" field.
	DefaultPrivProtocol string
	// DefaultPrivPassphrase holds the default value on creation for the "priv_passphrase" field.
	DefaultPrivPassphrase string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the CredentialProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// BySecLevel orders the results by the sec_level field.
func BySecLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecLevel, opts...).ToFunc()
}

// ByCommunity orders the results by the community field.
func ByCommunity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommunity, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByAuthProtocol orders the results by the auth_protocol field.
func ByAuthProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthProtocol, opts...).ToFunc()
}

// ByAuthPassphrase orders the results by the auth_passphrase field.
func ByAuthPassphrase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthPassphrase, opts...).ToFunc()
}

// ByPrivProtocol orders the results by the priv_protocol field.
func ByPrivProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivProtocol, opts...).ToFunc()
}

// ByPrivPassphrase orders the results by the priv_passphrase field.
func ByPrivPassphrase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivPassphrase, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
