// Code generated by ent, DO NOT EDIT.

package credentialprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/sh0jitmy/musubi/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldName, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldVersion, v))
}

// SecLevel applies equality check predicate on the "sec_level" field. It's identical to SecLevelEQ.
func SecLevel(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldSecLevel, v))
}

// Community applies equality check predicate on the "community" field. It's identical to CommunityEQ.
func Community(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldCommunity, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldUsername, v))
}

// AuthProtocol applies equality check predicate on the "auth_protocol" field. It's identical to AuthProtocolEQ.
func AuthProtocol(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldAuthProtocol, v))
}

// AuthPassphrase applies equality check predicate on the "auth_passphrase" field. It's identical to AuthPassphraseEQ.
func AuthPassphrase(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldAuthPassphrase, v))
}

// PrivProtocol applies equality check predicate on the "priv_protocol" field. It's identical to PrivProtocolEQ.
func PrivProtocol(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldPrivProtocol, v))
}

// PrivPassphrase applies equality check predicate on the "priv_passphrase" field. It's identical to PrivPassphraseEQ.
func PrivPassphrase(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldPrivPassphrase, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContainsFold(FieldName, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContainsFold(FieldVersion, v))
}

// SecLevelEQ applies the EQ predicate on the "sec_level" field.
func SecLevelEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldSecLevel, v))
}

// SecLevelNEQ applies the NEQ predicate on the "sec_level" field.
func SecLevelNEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldSecLevel, v))
}

// SecLevelIn applies the In predicate on the "sec_level" field.
func SecLevelIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldSecLevel, vs...))
}

// SecLevelNotIn applies the NotIn predicate on the "sec_level" field.
func SecLevelNotIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldSecLevel, vs...))
}

// SecLevelGT applies the GT predicate on the "sec_level" field.
func SecLevelGT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldSecLevel, v))
}

// SecLevelGTE applies the GTE predicate on the "sec_level" field.
func SecLevelGTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldSecLevel, v))
}

// SecLevelLT applies the LT predicate on the "sec_level" field.
func SecLevelLT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldSecLevel, v))
}

// SecLevelLTE applies the LTE predicate on the "sec_level" field.
func SecLevelLTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldSecLevel, v))
}

// SecLevelContains applies the Contains predicate on the "sec_level" field.
func SecLevelContains(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContains(FieldSecLevel, v))
}

// SecLevelHasPrefix applies the HasPrefix predicate on the "sec_level" field.
func SecLevelHasPrefix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasPrefix(FieldSecLevel, v))
}

// SecLevelHasSuffix applies the HasSuffix predicate on the "sec_level" field.
func SecLevelHasSuffix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasSuffix(FieldSecLevel, v))
}

// SecLevelEqualFold applies the EqualFold predicate on the "sec_level" field.
func SecLevelEqualFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEqualFold(FieldSecLevel, v))
}

// SecLevelContainsFold applies the ContainsFold predicate on the "sec_level" field.
func SecLevelContainsFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContainsFold(FieldSecLevel, v))
}

// CommunityEQ applies the EQ predicate on the "community" field.
func CommunityEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldCommunity, v))
}

// CommunityNEQ applies the NEQ predicate on the "community" field.
func CommunityNEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldCommunity, v))
}

// CommunityIn applies the In predicate on the "community" field.
func CommunityIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldCommunity, vs...))
}

// CommunityNotIn applies the NotIn predicate on the "community" field.
func CommunityNotIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldCommunity, vs...))
}

// CommunityGT applies the GT predicate on the "community" field.
func CommunityGT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldCommunity, v))
}

// CommunityGTE applies the GTE predicate on the "community" field.
func CommunityGTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldCommunity, v))
}

// CommunityLT applies the LT predicate on the "community" field.
func CommunityLT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldCommunity, v))
}

// CommunityLTE applies the LTE predicate on the "community" field.
func CommunityLTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldCommunity, v))
}

// CommunityContains applies the Contains predicate on the "community" field.
func CommunityContains(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContains(FieldCommunity, v))
}

// CommunityHasPrefix applies the HasPrefix predicate on the "community" field.
func CommunityHasPrefix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasPrefix(FieldCommunity, v))
}

// CommunityHasSuffix applies the HasSuffix predicate on the "community" field.
func CommunityHasSuffix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasSuffix(FieldCommunity, v))
}

// CommunityIsNil applies the IsNil predicate on the "community" field.
func CommunityIsNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIsNull(FieldCommunity))
}

// CommunityNotNil applies the NotNil predicate on the "community" field.
func CommunityNotNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotNull(FieldCommunity))
}

// CommunityEqualFold applies the EqualFold predicate on the "community" field.
func CommunityEqualFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEqualFold(FieldCommunity, v))
}

// CommunityContainsFold applies the ContainsFold predicate on the "community" field.
func CommunityContainsFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContainsFold(FieldCommunity, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContainsFold(FieldUsername, v))
}

// AuthProtocolEQ applies the EQ predicate on the "auth_protocol" field.
func AuthProtocolEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldAuthProtocol, v))
}

// AuthProtocolNEQ applies the NEQ predicate on the "auth_protocol" field.
func AuthProtocolNEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldAuthProtocol, v))
}

// AuthProtocolIn applies the In predicate on the "auth_protocol" field.
func AuthProtocolIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldAuthProtocol, vs...))
}

// AuthProtocolNotIn applies the NotIn predicate on the "auth_protocol" field.
func AuthProtocolNotIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldAuthProtocol, vs...))
}

// AuthProtocolGT applies the GT predicate on the "auth_protocol" field.
func AuthProtocolGT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldAuthProtocol, v))
}

// AuthProtocolGTE applies the GTE predicate on the "auth_protocol" field.
func AuthProtocolGTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldAuthProtocol, v))
}

// AuthProtocolLT applies the LT predicate on the "auth_protocol" field.
func AuthProtocolLT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldAuthProtocol, v))
}

// AuthProtocolLTE applies the LTE predicate on the "auth_protocol" field.
func AuthProtocolLTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldAuthProtocol, v))
}

// AuthProtocolContains applies the Contains predicate on the "auth_protocol" field.
func AuthProtocolContains(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContains(FieldAuthProtocol, v))
}

// AuthProtocolHasPrefix applies the HasPrefix predicate on the "auth_protocol" field.
func AuthProtocolHasPrefix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasPrefix(FieldAuthProtocol, v))
}

// AuthProtocolHasSuffix applies the HasSuffix predicate on the "auth_protocol" field.
func AuthProtocolHasSuffix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasSuffix(FieldAuthProtocol, v))
}

// AuthProtocolIsNil applies the IsNil predicate on the "auth_protocol" field.
func AuthProtocolIsNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIsNull(FieldAuthProtocol))
}

// AuthProtocolNotNil applies the NotNil predicate on the "auth_protocol" field.
func AuthProtocolNotNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotNull(FieldAuthProtocol))
}

// AuthProtocolEqualFold applies the EqualFold predicate on the "auth_protocol" field.
func AuthProtocolEqualFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEqualFold(FieldAuthProtocol, v))
}

// AuthProtocolContainsFold applies the ContainsFold predicate on the "auth_protocol" field.
func AuthProtocolContainsFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContainsFold(FieldAuthProtocol, v))
}

// AuthPassphraseEQ applies the EQ predicate on the "auth_passphrase" field.
func AuthPassphraseEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldAuthPassphrase, v))
}

// AuthPassphraseNEQ applies the NEQ predicate on the "auth_passphrase" field.
func AuthPassphraseNEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldAuthPassphrase, v))
}

// AuthPassphraseIn applies the In predicate on the "auth_passphrase" field.
func AuthPassphraseIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldAuthPassphrase, vs...))
}

// AuthPassphraseNotIn applies the NotIn predicate on the "auth_passphrase" field.
func AuthPassphraseNotIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldAuthPassphrase, vs...))
}

// AuthPassphraseGT applies the GT predicate on the "auth_passphrase" field.
func AuthPassphraseGT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldAuthPassphrase, v))
}

// AuthPassphraseGTE applies the GTE predicate on the "auth_passphrase" field.
func AuthPassphraseGTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldAuthPassphrase, v))
}

// AuthPassphraseLT applies the LT predicate on the "auth_passphrase" field.
func AuthPassphraseLT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldAuthPassphrase, v))
}

// AuthPassphraseLTE applies the LTE predicate on the "auth_passphrase" field.
func AuthPassphraseLTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldAuthPassphrase, v))
}

// AuthPassphraseContains applies the Contains predicate on the "auth_passphrase" field.
func AuthPassphraseContains(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContains(FieldAuthPassphrase, v))
}

// AuthPassphraseHasPrefix applies the HasPrefix predicate on the "auth_passphrase" field.
func AuthPassphraseHasPrefix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasPrefix(FieldAuthPassphrase, v))
}

// AuthPassphraseHasSuffix applies the HasSuffix predicate on the "auth_passphrase" field.
func AuthPassphraseHasSuffix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasSuffix(FieldAuthPassphrase, v))
}

// AuthPassphraseIsNil applies the IsNil predicate on the "auth_passphrase" field.
func AuthPassphraseIsNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIsNull(FieldAuthPassphrase))
}

// AuthPassphraseNotNil applies the NotNil predicate on the "auth_passphrase" field.
func AuthPassphraseNotNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotNull(FieldAuthPassphrase))
}

// AuthPassphraseEqualFold applies the EqualFold predicate on the "auth_passphrase" field.
func AuthPassphraseEqualFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEqualFold(FieldAuthPassphrase, v))
}

// AuthPassphraseContainsFold applies the ContainsFold predicate on the "auth_passphrase" field.
func AuthPassphraseContainsFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContainsFold(FieldAuthPassphrase, v))
}

// PrivProtocolEQ applies the EQ predicate on the "priv_protocol" field.
func PrivProtocolEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldPrivProtocol, v))
}

// PrivProtocolNEQ applies the NEQ predicate on the "priv_protocol" field.
func PrivProtocolNEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldPrivProtocol, v))
}

// PrivProtocolIn applies the In predicate on the "priv_protocol" field.
func PrivProtocolIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldPrivProtocol, vs...))
}

// PrivProtocolNotIn applies the NotIn predicate on the "priv_protocol" field.
func PrivProtocolNotIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldPrivProtocol, vs...))
}

// PrivProtocolGT applies the GT predicate on the "priv_protocol" field.
func PrivProtocolGT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldPrivProtocol, v))
}

// PrivProtocolGTE applies the GTE predicate on the "priv_protocol" field.
func PrivProtocolGTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldPrivProtocol, v))
}

// PrivProtocolLT applies the LT predicate on the "priv_protocol" field.
func PrivProtocolLT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldPrivProtocol, v))
}

// PrivProtocolLTE applies the LTE predicate on the "priv_protocol" field.
func PrivProtocolLTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldPrivProtocol, v))
}

// PrivProtocolContains applies the Contains predicate on the "priv_protocol" field.
func PrivProtocolContains(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContains(FieldPrivProtocol, v))
}

// PrivProtocolHasPrefix applies the HasPrefix predicate on the "priv_protocol" field.
func PrivProtocolHasPrefix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasPrefix(FieldPrivProtocol, v))
}

// PrivProtocolHasSuffix applies the HasSuffix predicate on the "priv_protocol" field.
func PrivProtocolHasSuffix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasSuffix(FieldPrivProtocol, v))
}

// PrivProtocolIsNil applies the IsNil predicate on the "priv_protocol" field.
func PrivProtocolIsNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIsNull(FieldPrivProtocol))
}

// PrivProtocolNotNil applies the NotNil predicate on the "priv_protocol" field.
func PrivProtocolNotNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotNull(FieldPrivProtocol))
}

// PrivProtocolEqualFold applies the EqualFold predicate on the "priv_protocol" field.
func PrivProtocolEqualFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEqualFold(FieldPrivProtocol, v))
}

// PrivProtocolContainsFold applies the ContainsFold predicate on the "priv_protocol" field.
func PrivProtocolContainsFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContainsFold(FieldPrivProtocol, v))
}

// PrivPassphraseEQ applies the EQ predicate on the "priv_passphrase" field.
func PrivPassphraseEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldPrivPassphrase, v))
}

// PrivPassphraseNEQ applies the NEQ predicate on the "priv_passphrase" field.
func PrivPassphraseNEQ(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldPrivPassphrase, v))
}

// PrivPassphraseIn applies the In predicate on the "priv_passphrase" field.
func PrivPassphraseIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldPrivPassphrase, vs...))
}

// PrivPassphraseNotIn applies the NotIn predicate on the "priv_passphrase" field.
func PrivPassphraseNotIn(vs ...string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldPrivPassphrase, vs...))
}

// PrivPassphraseGT applies the GT predicate on the "priv_passphrase" field.
func PrivPassphraseGT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldPrivPassphrase, v))
}

// PrivPassphraseGTE applies the GTE predicate on the "priv_passphrase" field.
func PrivPassphraseGTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldPrivPassphrase, v))
}

// PrivPassphraseLT applies the LT predicate on the "priv_passphrase" field.
func PrivPassphraseLT(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldPrivPassphrase, v))
}

// PrivPassphraseLTE applies the LTE predicate on the "priv_passphrase" field.
func PrivPassphraseLTE(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldPrivPassphrase, v))
}

// PrivPassphraseContains applies the Contains predicate on the "priv_passphrase" field.
func PrivPassphraseContains(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContains(FieldPrivPassphrase, v))
}

// PrivPassphraseHasPrefix applies the HasPrefix predicate on the "priv_passphrase" field.
func PrivPassphraseHasPrefix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasPrefix(FieldPrivPassphrase, v))
}

// PrivPassphraseHasSuffix applies the HasSuffix predicate on the "priv_passphrase" field.
func PrivPassphraseHasSuffix(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldHasSuffix(FieldPrivPassphrase, v))
}

// PrivPassphraseIsNil applies the IsNil predicate on the "priv_passphrase" field.
func PrivPassphraseIsNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIsNull(FieldPrivPassphrase))
}

// PrivPassphraseNotNil applies the NotNil predicate on the "priv_passphrase" field.
func PrivPassphraseNotNil() predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotNull(FieldPrivPassphrase))
}

// PrivPassphraseEqualFold applies the EqualFold predicate on the "priv_passphrase" field.
func PrivPassphraseEqualFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEqualFold(FieldPrivPassphrase, v))
}

// PrivPassphraseContainsFold applies the ContainsFold predicate on the "priv_passphrase" field.
func PrivPassphraseContainsFold(v string) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldContainsFold(FieldPrivPassphrase, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CredentialProfile) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CredentialProfile) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CredentialProfile) predicate.CredentialProfile {
	return predicate.CredentialProfile(sql.NotPredicates(p))
}
