// Code generated by ent, DO NOT EDIT.

package statetransitionlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shjtmy/go_sh0jitmy_template/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContainsFold(FieldID, id))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldTarget, v))
}

// StateKey applies equality check predicate on the "state_key" field. It's identical to StateKeyEQ.
func StateKey(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldStateKey, v))
}

// OldValue applies equality check predicate on the "old_value" field. It's identical to OldValueEQ.
func OldValue(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldOldValue, v))
}

// NewValue applies equality check predicate on the "new_value" field. It's identical to NewValueEQ.
func NewValue(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldNewValue, v))
}

// Trigger applies equality check predicate on the "trigger" field. It's identical to TriggerEQ.
func Trigger(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldTrigger, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldCreatedAt, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContainsFold(FieldTarget, v))
}

// StateKeyEQ applies the EQ predicate on the "state_key" field.
func StateKeyEQ(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldStateKey, v))
}

// StateKeyNEQ applies the NEQ predicate on the "state_key" field.
func StateKeyNEQ(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNEQ(FieldStateKey, v))
}

// StateKeyIn applies the In predicate on the "state_key" field.
func StateKeyIn(vs ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldIn(FieldStateKey, vs...))
}

// StateKeyNotIn applies the NotIn predicate on the "state_key" field.
func StateKeyNotIn(vs ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNotIn(FieldStateKey, vs...))
}

// StateKeyGT applies the GT predicate on the "state_key" field.
func StateKeyGT(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGT(FieldStateKey, v))
}

// StateKeyGTE applies the GTE predicate on the "state_key" field.
func StateKeyGTE(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGTE(FieldStateKey, v))
}

// StateKeyLT applies the LT predicate on the "state_key" field.
func StateKeyLT(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLT(FieldStateKey, v))
}

// StateKeyLTE applies the LTE predicate on the "state_key" field.
func StateKeyLTE(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLTE(FieldStateKey, v))
}

// StateKeyContains applies the Contains predicate on the "state_key" field.
func StateKeyContains(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContains(FieldStateKey, v))
}

// StateKeyHasPrefix applies the HasPrefix predicate on the "state_key" field.
func StateKeyHasPrefix(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldHasPrefix(FieldStateKey, v))
}

// StateKeyHasSuffix applies the HasSuffix predicate on the "state_key" field.
func StateKeyHasSuffix(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldHasSuffix(FieldStateKey, v))
}

// StateKeyEqualFold applies the EqualFold predicate on the "state_key" field.
func StateKeyEqualFold(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEqualFold(FieldStateKey, v))
}

// StateKeyContainsFold applies the ContainsFold predicate on the "state_key" field.
func StateKeyContainsFold(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContainsFold(FieldStateKey, v))
}

// OldValueEQ applies the EQ predicate on the "old_value" field.
func OldValueEQ(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldOldValue, v))
}

// OldValueNEQ applies the NEQ predicate on the "old_value" field.
func OldValueNEQ(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNEQ(FieldOldValue, v))
}

// OldValueIn applies the In predicate on the "old_value" field.
func OldValueIn(vs ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldIn(FieldOldValue, vs...))
}

// OldValueNotIn applies the NotIn predicate on the "old_value" field.
func OldValueNotIn(vs ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNotIn(FieldOldValue, vs...))
}

// OldValueGT applies the GT predicate on the "old_value" field.
func OldValueGT(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGT(FieldOldValue, v))
}

// OldValueGTE applies the GTE predicate on the "old_value" field.
func OldValueGTE(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGTE(FieldOldValue, v))
}

// OldValueLT applies the LT predicate on the "old_value" field.
func OldValueLT(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLT(FieldOldValue, v))
}

// OldValueLTE applies the LTE predicate on the "old_value" field.
func OldValueLTE(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLTE(FieldOldValue, v))
}

// OldValueContains applies the Contains predicate on the "old_value" field.
func OldValueContains(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContains(FieldOldValue, v))
}

// OldValueHasPrefix applies the HasPrefix predicate on the "old_value" field.
func OldValueHasPrefix(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldHasPrefix(FieldOldValue, v))
}

// OldValueHasSuffix applies the HasSuffix predicate on the "old_value" field.
func OldValueHasSuffix(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldHasSuffix(FieldOldValue, v))
}

// OldValueEqualFold applies the EqualFold predicate on the "old_value" field.
func OldValueEqualFold(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEqualFold(FieldOldValue, v))
}

// OldValueContainsFold applies the ContainsFold predicate on the "old_value" field.
func OldValueContainsFold(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContainsFold(FieldOldValue, v))
}

// NewValueEQ applies the EQ predicate on the "new_value" field.
func NewValueEQ(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldNewValue, v))
}

// NewValueNEQ applies the NEQ predicate on the "new_value" field.
func NewValueNEQ(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNEQ(FieldNewValue, v))
}

// NewValueIn applies the In predicate on the "new_value" field.
func NewValueIn(vs ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldIn(FieldNewValue, vs...))
}

// NewValueNotIn applies the NotIn predicate on the "new_value" field.
func NewValueNotIn(vs ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNotIn(FieldNewValue, vs...))
}

// NewValueGT applies the GT predicate on the "new_value" field.
func NewValueGT(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGT(FieldNewValue, v))
}

// NewValueGTE applies the GTE predicate on the "new_value" field.
func NewValueGTE(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGTE(FieldNewValue, v))
}

// NewValueLT applies the LT predicate on the "new_value" field.
func NewValueLT(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLT(FieldNewValue, v))
}

// NewValueLTE applies the LTE predicate on the "new_value" field.
func NewValueLTE(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLTE(FieldNewValue, v))
}

// NewValueContains applies the Contains predicate on the "new_value" field.
func NewValueContains(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContains(FieldNewValue, v))
}

// NewValueHasPrefix applies the HasPrefix predicate on the "new_value" field.
func NewValueHasPrefix(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldHasPrefix(FieldNewValue, v))
}

// NewValueHasSuffix applies the HasSuffix predicate on the "new_value" field.
func NewValueHasSuffix(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldHasSuffix(FieldNewValue, v))
}

// NewValueEqualFold applies the EqualFold predicate on the "new_value" field.
func NewValueEqualFold(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEqualFold(FieldNewValue, v))
}

// NewValueContainsFold applies the ContainsFold predicate on the "new_value" field.
func NewValueContainsFold(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContainsFold(FieldNewValue, v))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldTrigger, v))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNEQ(FieldTrigger, v))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldIn(FieldTrigger, vs...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNotIn(FieldTrigger, vs...))
}

// TriggerGT applies the GT predicate on the "trigger" field.
func TriggerGT(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGT(FieldTrigger, v))
}

// TriggerGTE applies the GTE predicate on the "trigger" field.
func TriggerGTE(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGTE(FieldTrigger, v))
}

// TriggerLT applies the LT predicate on the "trigger" field.
func TriggerLT(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLT(FieldTrigger, v))
}

// TriggerLTE applies the LTE predicate on the "trigger" field.
func TriggerLTE(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLTE(FieldTrigger, v))
}

// TriggerContains applies the Contains predicate on the "trigger" field.
func TriggerContains(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContains(FieldTrigger, v))
}

// TriggerHasPrefix applies the HasPrefix predicate on the "trigger" field.
func TriggerHasPrefix(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldHasPrefix(FieldTrigger, v))
}

// TriggerHasSuffix applies the HasSuffix predicate on the "trigger" field.
func TriggerHasSuffix(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldHasSuffix(FieldTrigger, v))
}

// TriggerEqualFold applies the EqualFold predicate on the "trigger" field.
func TriggerEqualFold(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEqualFold(FieldTrigger, v))
}

// TriggerContainsFold applies the ContainsFold predicate on the "trigger" field.
func TriggerContainsFold(v string) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldContainsFold(FieldTrigger, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StateTransitionLog) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StateTransitionLog) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StateTransitionLog) predicate.StateTransitionLog {
	return predicate.StateTransitionLog(sql.NotPredicates(p))
}
