// Code generated by ent, DO NOT EDIT.

package scenarioversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the scenarioversion type in the database.
	Label = "scenario_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldScenarioID holds the string denoting the scenario_id field in the database.
	FieldScenarioID = "scenario_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldDslYaml holds the string denoting the dsl_yaml field in the database.
	FieldDslYaml = "dsl_yaml"
	// FieldInputsSchema holds the string denoting the inputs_schema field in the database.
	FieldInputsSchema = "inputs_schema"
	// FieldTargetNames holds the string denoting the target_names field in the database.
	FieldTargetNames = "target_names"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the scenarioversion in the database.
	Table = "scenario_versions"
)

// Columns holds all SQL columns for scenarioversion fields.
var Columns = []string{
	FieldID,
	FieldScenarioID,
	FieldVersion,
	FieldDslYaml,
	FieldInputsSchema,
	FieldTargetNames,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ScenarioIDValidator is a validator for the "scenario_id" field. It is called by the builders before save.
	ScenarioIDValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
	// DslYamlValidator is a validator for the "dsl_yaml" field. It is called by the builders before save.
	DslYamlValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the ScenarioVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByScenarioID orders the results by the scenario_id field.
func ByScenarioID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScenarioID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByDslYaml orders the results by the dsl_yaml field.
func ByDslYaml(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDslYaml, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
