// Code generated by ent, DO NOT EDIT.

package scenarioversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shjtmy/go_sh0jitmy_template/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldContainsFold(FieldID, id))
}

// ScenarioID applies equality check predicate on the "scenario_id" field. It's identical to ScenarioIDEQ.
func ScenarioID(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEQ(FieldScenarioID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEQ(FieldVersion, v))
}

// DslYaml applies equality check predicate on the "dsl_yaml" field. It's identical to DslYamlEQ.
func DslYaml(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEQ(FieldDslYaml, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// ScenarioIDEQ applies the EQ predicate on the "scenario_id" field.
func ScenarioIDEQ(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEQ(FieldScenarioID, v))
}

// ScenarioIDNEQ applies the NEQ predicate on the "scenario_id" field.
func ScenarioIDNEQ(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNEQ(FieldScenarioID, v))
}

// ScenarioIDIn applies the In predicate on the "scenario_id" field.
func ScenarioIDIn(vs ...string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldIn(FieldScenarioID, vs...))
}

// ScenarioIDNotIn applies the NotIn predicate on the "scenario_id" field.
func ScenarioIDNotIn(vs ...string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNotIn(FieldScenarioID, vs...))
}

// ScenarioIDGT applies the GT predicate on the "scenario_id" field.
func ScenarioIDGT(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldGT(FieldScenarioID, v))
}

// ScenarioIDGTE applies the GTE predicate on the "scenario_id" field.
func ScenarioIDGTE(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldGTE(FieldScenarioID, v))
}

// ScenarioIDLT applies the LT predicate on the "scenario_id" field.
func ScenarioIDLT(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldLT(FieldScenarioID, v))
}

// ScenarioIDLTE applies the LTE predicate on the "scenario_id" field.
func ScenarioIDLTE(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldLTE(FieldScenarioID, v))
}

// ScenarioIDContains applies the Contains predicate on the "scenario_id" field.
func ScenarioIDContains(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldContains(FieldScenarioID, v))
}

// ScenarioIDHasPrefix applies the HasPrefix predicate on the "scenario_id" field.
func ScenarioIDHasPrefix(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldHasPrefix(FieldScenarioID, v))
}

// ScenarioIDHasSuffix applies the HasSuffix predicate on the "scenario_id" field.
func ScenarioIDHasSuffix(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldHasSuffix(FieldScenarioID, v))
}

// ScenarioIDEqualFold applies the EqualFold predicate on the "scenario_id" field.
func ScenarioIDEqualFold(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEqualFold(FieldScenarioID, v))
}

// ScenarioIDContainsFold applies the ContainsFold predicate on the "scenario_id" field.
func ScenarioIDContainsFold(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldContainsFold(FieldScenarioID, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldLTE(FieldVersion, v))
}

// DslYamlEQ applies the EQ predicate on the "dsl_yaml" field.
func DslYamlEQ(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEQ(FieldDslYaml, v))
}

// DslYamlNEQ applies the NEQ predicate on the "dsl_yaml" field.
func DslYamlNEQ(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNEQ(FieldDslYaml, v))
}

// DslYamlIn applies the In predicate on the "dsl_yaml" field.
func DslYamlIn(vs ...string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldIn(FieldDslYaml, vs...))
}

// DslYamlNotIn applies the NotIn predicate on the "dsl_yaml" field.
func DslYamlNotIn(vs ...string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNotIn(FieldDslYaml, vs...))
}

// DslYamlGT applies the GT predicate on the "dsl_yaml" field.
func DslYamlGT(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldGT(FieldDslYaml, v))
}

// DslYamlGTE applies the GTE predicate on the "dsl_yaml" field.
func DslYamlGTE(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldGTE(FieldDslYaml, v))
}

// DslYamlLT applies the LT predicate on the "dsl_yaml" field.
func DslYamlLT(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldLT(FieldDslYaml, v))
}

// DslYamlLTE applies the LTE predicate on the "dsl_yaml" field.
func DslYamlLTE(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldLTE(FieldDslYaml, v))
}

// DslYamlContains applies the Contains predicate on the "dsl_yaml" field.
func DslYamlContains(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldContains(FieldDslYaml, v))
}

// DslYamlHasPrefix applies the HasPrefix predicate on the "dsl_yaml" field.
func DslYamlHasPrefix(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldHasPrefix(FieldDslYaml, v))
}

// DslYamlHasSuffix applies the HasSuffix predicate on the "dsl_yaml" field.
func DslYamlHasSuffix(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldHasSuffix(FieldDslYaml, v))
}

// DslYamlEqualFold applies the EqualFold predicate on the "dsl_yaml" field.
func DslYamlEqualFold(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEqualFold(FieldDslYaml, v))
}

// DslYamlContainsFold applies the ContainsFold predicate on the "dsl_yaml" field.
func DslYamlContainsFold(v string) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldContainsFold(FieldDslYaml, v))
}

// InputsSchemaIsNil applies the IsNil predicate on the "inputs_schema" field.
func InputsSchemaIsNil() predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldIsNull(FieldInputsSchema))
}

// InputsSchemaNotNil applies the NotNil predicate on the "inputs_schema" field.
func InputsSchemaNotNil() predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNotNull(FieldInputsSchema))
}

// TargetNamesIsNil applies the IsNil predicate on the "target_names" field.
func TargetNamesIsNil() predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldIsNull(FieldTargetNames))
}

// TargetNamesNotNil applies the NotNil predicate on the "target_names" field.
func TargetNamesNotNil() predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNotNull(FieldTargetNames))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScenarioVersion) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScenarioVersion) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScenarioVersion) predicate.ScenarioVersion {
	return predicate.ScenarioVersion(sql.NotPredicates(p))
}
