// Code generated by ent, DO NOT EDIT.

package jobstep

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the jobstep type in the database.
	Label = "job_step"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldStepID holds the string denoting the step_id field in the database.
	FieldStepID = "step_id"
	// FieldStepOrder holds the string denoting the step_order field in the database.
	FieldStepOrder = "step_order"
	// FieldStepType holds the string denoting the step_type field in the database.
	FieldStepType = "step_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldResultOutput holds the string denoting the result_output field in the database.
	FieldResultOutput = "result_output"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldExecutedAt holds the string denoting the executed_at field in the database.
	FieldExecutedAt = "executed_at"
	// Table holds the table name of the jobstep in the database.
	Table = "job_steps"
)

// Columns holds all SQL columns for jobstep fields.
var Columns = []string{
	FieldID,
	FieldJobID,
	FieldStepID,
	FieldStepOrder,
	FieldStepType,
	FieldStatus,
	FieldResultOutput,
	FieldError,
	FieldExecutedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// JobIDValidator is a validator for the "job_id" field. It is called by the builders before save.
	JobIDValidator func(string) error
	// StepIDValidator is a validator for the "step_id" field. It is called by the builders before save.
	StepIDValidator func(string) error
	// DefaultStepOrder holds the default value on creation for the "step_order" field.
	DefaultStepOrder int
	// StepTypeValidator is a validator for the "step_type" field. It is called by the builders before save.
	StepTypeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultError holds the default value on creation for the "error" field.
	DefaultError string
	// DefaultExecutedAt holds the default value on creation for the "executed_at" field.
	DefaultExecutedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the JobStep queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByStepID orders the results by the step_id field.
func ByStepID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepID, opts...).ToFunc()
}

// ByStepOrder orders the results by the step_order field.
func ByStepOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepOrder, opts...).ToFunc()
}

// ByStepType orders the results by the step_type field.
func ByStepType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByExecutedAt orders the results by the executed_at field.
func ByExecutedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutedAt, opts...).ToFunc()
}
