// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shjtmy/go_sh0jitmy_template/ent/credentialprofile"
)

// CredentialProfileCreate is the builder for creating a CredentialProfile entity.
type CredentialProfileCreate struct {
	config
	mutation *CredentialProfileMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CredentialProfileCreate) SetName(v string) *CredentialProfileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *CredentialProfileCreate) SetVersion(v string) *CredentialProfileCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *CredentialProfileCreate) SetNillableVersion(v *string) *CredentialProfileCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetSecLevel sets the "sec_level" field.
func (_c *CredentialProfileCreate) SetSecLevel(v string) *CredentialProfileCreate {
	_c.mutation.SetSecLevel(v)
	return _c
}

// SetNillableSecLevel sets the "sec_level" field if the given value is not nil.
func (_c *CredentialProfileCreate) SetNillableSecLevel(v *string) *CredentialProfileCreate {
	if v != nil {
		_c.SetSecLevel(*v)
	}
	return _c
}

// SetCommunity sets the "community" field.
func (_c *CredentialProfileCreate) SetCommunity(v string) *CredentialProfileCreate {
	_c.mutation.SetCommunity(v)
	return _c
}

// SetNillableCommunity sets the "community" field if the given value is not nil.
func (_c *CredentialProfileCreate) SetNillableCommunity(v *string) *CredentialProfileCreate {
	if v != nil {
		_c.SetCommunity(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *CredentialProfileCreate) SetUsername(v string) *CredentialProfileCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *CredentialProfileCreate) SetNillableUsername(v *string) *CredentialProfileCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetAuthProtocol sets the "auth_protocol" field.
func (_c *CredentialProfileCreate) SetAuthProtocol(v string) *CredentialProfileCreate {
	_c.mutation.SetAuthProtocol(v)
	return _c
}

// SetNillableAuthProtocol sets the "auth_protocol" field if the given value is not nil.
func (_c *CredentialProfileCreate) SetNillableAuthProtocol(v *string) *CredentialProfileCreate {
	if v != nil {
		_c.SetAuthProtocol(*v)
	}
	return _c
}

// SetAuthPassphrase sets the "auth_passphrase" field.
func (_c *CredentialProfileCreate) SetAuthPassphrase(v string) *CredentialProfileCreate {
	_c.mutation.SetAuthPassphrase(v)
	return _c
}

// SetNillableAuthPassphrase sets the "auth_passphrase" field if the given value is not nil.
func (_c *CredentialProfileCreate) SetNillableAuthPassphrase(v *string) *CredentialProfileCreate {
	if v != nil {
		_c.SetAuthPassphrase(*v)
	}
	return _c
}

// SetPrivProtocol sets the "priv_protocol" field.
func (_c *CredentialProfileCreate) SetPrivProtocol(v string) *CredentialProfileCreate {
	_c.mutation.SetPrivProtocol(v)
	return _c
}

// SetNillablePrivProtocol sets the "priv_protocol" field if the given value is not nil.
func (_c *CredentialProfileCreate) SetNillablePrivProtocol(v *string) *CredentialProfileCreate {
	if v != nil {
		_c.SetPrivProtocol(*v)
	}
	return _c
}

// SetPrivPassphrase sets the "priv_passphrase" field.
func (_c *CredentialProfileCreate) SetPrivPassphrase(v string) *CredentialProfileCreate {
	_c.mutation.SetPrivPassphrase(v)
	return _c
}

// SetNillablePrivPassphrase sets the "priv_passphrase" field if the given value is not nil.
func (_c *CredentialProfileCreate) SetNillablePrivPassphrase(v *string) *CredentialProfileCreate {
	if v != nil {
		_c.SetPrivPassphrase(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CredentialProfileCreate) SetCreatedAt(v time.Time) *CredentialProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CredentialProfileCreate) SetNillableCreatedAt(v *time.Time) *CredentialProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CredentialProfileCreate) SetUpdatedAt(v time.Time) *CredentialProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CredentialProfileCreate) SetNillableUpdatedAt(v *time.Time) *CredentialProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CredentialProfileCreate) SetID(v string) *CredentialProfileCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CredentialProfileMutation object of the builder.
func (_c *CredentialProfileCreate) Mutation() *CredentialProfileMutation {
	return _c.mutation
}

// Save creates the CredentialProfile in the database.
func (_c *CredentialProfileCreate) Save(ctx context.Context) (*CredentialProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CredentialProfileCreate) SaveX(ctx context.Context) *CredentialProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CredentialProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CredentialProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CredentialProfileCreate) defaults() {
	if _, ok := _c.mutation.Version(); !ok {
		v := credentialprofile.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.SecLevel(); !ok {
		v := credentialprofile.DefaultSecLevel
		_c.mutation.SetSecLevel(v)
	}
	if _, ok := _c.mutation.Community(); !ok {
		v := credentialprofile.DefaultCommunity
		_c.mutation.SetCommunity(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := credentialprofile.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.AuthProtocol(); !ok {
		v := credentialprofile.DefaultAuthProtocol
		_c.mutation.SetAuthProtocol(v)
	}
	if _, ok := _c.mutation.AuthPassphrase(); !ok {
		v := credentialprofile.DefaultAuthPassphrase
		_c.mutation.SetAuthPassphrase(v)
	}
	if _, ok := _c.mutation.PrivProtocol(); !ok {
		v := credentialprofile.DefaultPrivProtocol
		_c.mutation.SetPrivProtocol(v)
	}
	if _, ok := _c.mutation.PrivPassphrase(); !ok {
		v := credentialprofile.DefaultPrivPassphrase
		_c.mutation.SetPrivPassphrase(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := credentialprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := credentialprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CredentialProfileCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CredentialProfile.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := credentialprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CredentialProfile.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "CredentialProfile.version"`)}
	}
	if _, ok := _c.mutation.SecLevel(); !ok {
		return &ValidationError{Name: "sec_level", err: errors.New(`ent: missing required field "CredentialProfile.sec_level"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CredentialProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CredentialProfile.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := credentialprofile.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CredentialProfile.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CredentialProfileCreate) sqlSave(ctx context.Context) (*CredentialProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CredentialProfile.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CredentialProfileCreate) createSpec() (*CredentialProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &CredentialProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(credentialprofile.Table, sqlgraph.NewFieldSpec(credentialprofile.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(credentialprofile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(credentialprofile.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.SecLevel(); ok {
		_spec.SetField(credentialprofile.FieldSecLevel, field.TypeString, value)
		_node.SecLevel = value
	}
	if value, ok := _c.mutation.Community(); ok {
		_spec.SetField(credentialprofile.FieldCommunity, field.TypeString, value)
		_node.Community = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(credentialprofile.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.AuthProtocol(); ok {
		_spec.SetField(credentialprofile.FieldAuthProtocol, field.TypeString, value)
		_node.AuthProtocol = value
	}
	if value, ok := _c.mutation.AuthPassphrase(); ok {
		_spec.SetField(credentialprofile.FieldAuthPassphrase, field.TypeString, value)
		_node.AuthPassphrase = value
	}
	if value, ok := _c.mutation.PrivProtocol(); ok {
		_spec.SetField(credentialprofile.FieldPrivProtocol, field.TypeString, value)
		_node.PrivProtocol = value
	}
	if value, ok := _c.mutation.PrivPassphrase(); ok {
		_spec.SetField(credentialprofile.FieldPrivPassphrase, field.TypeString, value)
		_node.PrivPassphrase = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(credentialprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(credentialprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CredentialProfileCreateBulk is the builder for creating many CredentialProfile entities in bulk.
type CredentialProfileCreateBulk struct {
	config
	err      error
	builders []*CredentialProfileCreate
}

// Save creates the CredentialProfile entities in the database.
func (_c *CredentialProfileCreateBulk) Save(ctx context.Context) ([]*CredentialProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CredentialProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CredentialProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CredentialProfileCreateBulk) SaveX(ctx context.Context) []*CredentialProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CredentialProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CredentialProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
