// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shjtmy/go_sh0jitmy_template/ent/credentialprofile"
	"github.com/shjtmy/go_sh0jitmy_template/ent/predicate"
)

// CredentialProfileUpdate is the builder for updating CredentialProfile entities.
type CredentialProfileUpdate struct {
	config
	hooks    []Hook
	mutation *CredentialProfileMutation
}

// Where appends a list predicates to the CredentialProfileUpdate builder.
func (_u *CredentialProfileUpdate) Where(ps ...predicate.CredentialProfile) *CredentialProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CredentialProfileUpdate) SetName(v string) *CredentialProfileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CredentialProfileUpdate) SetNillableName(v *string) *CredentialProfileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *CredentialProfileUpdate) SetVersion(v string) *CredentialProfileUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CredentialProfileUpdate) SetNillableVersion(v *string) *CredentialProfileUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetSecLevel sets the "sec_level" field.
func (_u *CredentialProfileUpdate) SetSecLevel(v string) *CredentialProfileUpdate {
	_u.mutation.SetSecLevel(v)
	return _u
}

// SetNillableSecLevel sets the "sec_level" field if the given value is not nil.
func (_u *CredentialProfileUpdate) SetNillableSecLevel(v *string) *CredentialProfileUpdate {
	if v != nil {
		_u.SetSecLevel(*v)
	}
	return _u
}

// SetCommunity sets the "community" field.
func (_u *CredentialProfileUpdate) SetCommunity(v string) *CredentialProfileUpdate {
	_u.mutation.SetCommunity(v)
	return _u
}

// SetNillableCommunity sets the "community" field if the given value is not nil.
func (_u *CredentialProfileUpdate) SetNillableCommunity(v *string) *CredentialProfileUpdate {
	if v != nil {
		_u.SetCommunity(*v)
	}
	return _u
}

// ClearCommunity clears the value of the "community" field.
func (_u *CredentialProfileUpdate) ClearCommunity() *CredentialProfileUpdate {
	_u.mutation.ClearCommunity()
	return _u
}

// SetUsername sets the "username" field.
func (_u *CredentialProfileUpdate) SetUsername(v string) *CredentialProfileUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *CredentialProfileUpdate) SetNillableUsername(v *string) *CredentialProfileUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *CredentialProfileUpdate) ClearUsername() *CredentialProfileUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetAuthProtocol sets the "auth_protocol" field.
func (_u *CredentialProfileUpdate) SetAuthProtocol(v string) *CredentialProfileUpdate {
	_u.mutation.SetAuthProtocol(v)
	return _u
}

// SetNillableAuthProtocol sets the "auth_protocol" field if the given value is not nil.
func (_u *CredentialProfileUpdate) SetNillableAuthProtocol(v *string) *CredentialProfileUpdate {
	if v != nil {
		_u.SetAuthProtocol(*v)
	}
	return _u
}

// ClearAuthProtocol clears the value of the "auth_protocol" field.
func (_u *CredentialProfileUpdate) ClearAuthProtocol() *CredentialProfileUpdate {
	_u.mutation.ClearAuthProtocol()
	return _u
}

// SetAuthPassphrase sets the "auth_passphrase" field.
func (_u *CredentialProfileUpdate) SetAuthPassphrase(v string) *CredentialProfileUpdate {
	_u.mutation.SetAuthPassphrase(v)
	return _u
}

// SetNillableAuthPassphrase sets the "auth_passphrase" field if the given value is not nil.
func (_u *CredentialProfileUpdate) SetNillableAuthPassphrase(v *string) *CredentialProfileUpdate {
	if v != nil {
		_u.SetAuthPassphrase(*v)
	}
	return _u
}

// ClearAuthPassphrase clears the value of the "auth_passphrase" field.
func (_u *CredentialProfileUpdate) ClearAuthPassphrase() *CredentialProfileUpdate {
	_u.mutation.ClearAuthPassphrase()
	return _u
}

// SetPrivProtocol sets the "priv_protocol" field.
func (_u *CredentialProfileUpdate) SetPrivProtocol(v string) *CredentialProfileUpdate {
	_u.mutation.SetPrivProtocol(v)
	return _u
}

// SetNillablePrivProtocol sets the "priv_protocol" field if the given value is not nil.
func (_u *CredentialProfileUpdate) SetNillablePrivProtocol(v *string) *CredentialProfileUpdate {
	if v != nil {
		_u.SetPrivProtocol(*v)
	}
	return _u
}

// ClearPrivProtocol clears the value of the "priv_protocol" field.
func (_u *CredentialProfileUpdate) ClearPrivProtocol() *CredentialProfileUpdate {
	_u.mutation.ClearPrivProtocol()
	return _u
}

// SetPrivPassphrase sets the "priv_passphrase" field.
func (_u *CredentialProfileUpdate) SetPrivPassphrase(v string) *CredentialProfileUpdate {
	_u.mutation.SetPrivPassphrase(v)
	return _u
}

// SetNillablePrivPassphrase sets the "priv_passphrase" field if the given value is not nil.
func (_u *CredentialProfileUpdate) SetNillablePrivPassphrase(v *string) *CredentialProfileUpdate {
	if v != nil {
		_u.SetPrivPassphrase(*v)
	}
	return _u
}

// ClearPrivPassphrase clears the value of the "priv_passphrase" field.
func (_u *CredentialProfileUpdate) ClearPrivPassphrase() *CredentialProfileUpdate {
	_u.mutation.ClearPrivPassphrase()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialProfileUpdate) SetUpdatedAt(v time.Time) *CredentialProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CredentialProfileMutation object of the builder.
func (_u *CredentialProfileUpdate) Mutation() *CredentialProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CredentialProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CredentialProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := credentialprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CredentialProfileUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := credentialprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CredentialProfile.name": %w`, err)}
		}
	}
	return nil
}

func (_u *CredentialProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credentialprofile.Table, credentialprofile.Columns, sqlgraph.NewFieldSpec(credentialprofile.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(credentialprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(credentialprofile.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecLevel(); ok {
		_spec.SetField(credentialprofile.FieldSecLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Community(); ok {
		_spec.SetField(credentialprofile.FieldCommunity, field.TypeString, value)
	}
	if _u.mutation.CommunityCleared() {
		_spec.ClearField(credentialprofile.FieldCommunity, field.TypeString)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(credentialprofile.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(credentialprofile.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.AuthProtocol(); ok {
		_spec.SetField(credentialprofile.FieldAuthProtocol, field.TypeString, value)
	}
	if _u.mutation.AuthProtocolCleared() {
		_spec.ClearField(credentialprofile.FieldAuthProtocol, field.TypeString)
	}
	if value, ok := _u.mutation.AuthPassphrase(); ok {
		_spec.SetField(credentialprofile.FieldAuthPassphrase, field.TypeString, value)
	}
	if _u.mutation.AuthPassphraseCleared() {
		_spec.ClearField(credentialprofile.FieldAuthPassphrase, field.TypeString)
	}
	if value, ok := _u.mutation.PrivProtocol(); ok {
		_spec.SetField(credentialprofile.FieldPrivProtocol, field.TypeString, value)
	}
	if _u.mutation.PrivProtocolCleared() {
		_spec.ClearField(credentialprofile.FieldPrivProtocol, field.TypeString)
	}
	if value, ok := _u.mutation.PrivPassphrase(); ok {
		_spec.SetField(credentialprofile.FieldPrivPassphrase, field.TypeString, value)
	}
	if _u.mutation.PrivPassphraseCleared() {
		_spec.ClearField(credentialprofile.FieldPrivPassphrase, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credentialprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentialprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CredentialProfileUpdateOne is the builder for updating a single CredentialProfile entity.
type CredentialProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CredentialProfileMutation
}

// SetName sets the "name" field.
func (_u *CredentialProfileUpdateOne) SetName(v string) *CredentialProfileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CredentialProfileUpdateOne) SetNillableName(v *string) *CredentialProfileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *CredentialProfileUpdateOne) SetVersion(v string) *CredentialProfileUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CredentialProfileUpdateOne) SetNillableVersion(v *string) *CredentialProfileUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetSecLevel sets the "sec_level" field.
func (_u *CredentialProfileUpdateOne) SetSecLevel(v string) *CredentialProfileUpdateOne {
	_u.mutation.SetSecLevel(v)
	return _u
}

// SetNillableSecLevel sets the "sec_level" field if the given value is not nil.
func (_u *CredentialProfileUpdateOne) SetNillableSecLevel(v *string) *CredentialProfileUpdateOne {
	if v != nil {
		_u.SetSecLevel(*v)
	}
	return _u
}

// SetCommunity sets the "community" field.
func (_u *CredentialProfileUpdateOne) SetCommunity(v string) *CredentialProfileUpdateOne {
	_u.mutation.SetCommunity(v)
	return _u
}

// SetNillableCommunity sets the "community" field if the given value is not nil.
func (_u *CredentialProfileUpdateOne) SetNillableCommunity(v *string) *CredentialProfileUpdateOne {
	if v != nil {
		_u.SetCommunity(*v)
	}
	return _u
}

// ClearCommunity clears the value of the "community" field.
func (_u *CredentialProfileUpdateOne) ClearCommunity() *CredentialProfileUpdateOne {
	_u.mutation.ClearCommunity()
	return _u
}

// SetUsername sets the "username" field.
func (_u *CredentialProfileUpdateOne) SetUsername(v string) *CredentialProfileUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *CredentialProfileUpdateOne) SetNillableUsername(v *string) *CredentialProfileUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *CredentialProfileUpdateOne) ClearUsername() *CredentialProfileUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetAuthProtocol sets the "auth_protocol" field.
func (_u *CredentialProfileUpdateOne) SetAuthProtocol(v string) *CredentialProfileUpdateOne {
	_u.mutation.SetAuthProtocol(v)
	return _u
}

// SetNillableAuthProtocol sets the "auth_protocol" field if the given value is not nil.
func (_u *CredentialProfileUpdateOne) SetNillableAuthProtocol(v *string) *CredentialProfileUpdateOne {
	if v != nil {
		_u.SetAuthProtocol(*v)
	}
	return _u
}

// ClearAuthProtocol clears the value of the "auth_protocol" field.
func (_u *CredentialProfileUpdateOne) ClearAuthProtocol() *CredentialProfileUpdateOne {
	_u.mutation.ClearAuthProtocol()
	return _u
}

// SetAuthPassphrase sets the "auth_passphrase" field.
func (_u *CredentialProfileUpdateOne) SetAuthPassphrase(v string) *CredentialProfileUpdateOne {
	_u.mutation.SetAuthPassphrase(v)
	return _u
}

// SetNillableAuthPassphrase sets the "auth_passphrase" field if the given value is not nil.
func (_u *CredentialProfileUpdateOne) SetNillableAuthPassphrase(v *string) *CredentialProfileUpdateOne {
	if v != nil {
		_u.SetAuthPassphrase(*v)
	}
	return _u
}

// ClearAuthPassphrase clears the value of the "auth_passphrase" field.
func (_u *CredentialProfileUpdateOne) ClearAuthPassphrase() *CredentialProfileUpdateOne {
	_u.mutation.ClearAuthPassphrase()
	return _u
}

// SetPrivProtocol sets the "priv_protocol" field.
func (_u *CredentialProfileUpdateOne) SetPrivProtocol(v string) *CredentialProfileUpdateOne {
	_u.mutation.SetPrivProtocol(v)
	return _u
}

// SetNillablePrivProtocol sets the "priv_protocol" field if the given value is not nil.
func (_u *CredentialProfileUpdateOne) SetNillablePrivProtocol(v *string) *CredentialProfileUpdateOne {
	if v != nil {
		_u.SetPrivProtocol(*v)
	}
	return _u
}

// ClearPrivProtocol clears the value of the "priv_protocol" field.
func (_u *CredentialProfileUpdateOne) ClearPrivProtocol() *CredentialProfileUpdateOne {
	_u.mutation.ClearPrivProtocol()
	return _u
}

// SetPrivPassphrase sets the "priv_passphrase" field.
func (_u *CredentialProfileUpdateOne) SetPrivPassphrase(v string) *CredentialProfileUpdateOne {
	_u.mutation.SetPrivPassphrase(v)
	return _u
}

// SetNillablePrivPassphrase sets the "priv_passphrase" field if the given value is not nil.
func (_u *CredentialProfileUpdateOne) SetNillablePrivPassphrase(v *string) *CredentialProfileUpdateOne {
	if v != nil {
		_u.SetPrivPassphrase(*v)
	}
	return _u
}

// ClearPrivPassphrase clears the value of the "priv_passphrase" field.
func (_u *CredentialProfileUpdateOne) ClearPrivPassphrase() *CredentialProfileUpdateOne {
	_u.mutation.ClearPrivPassphrase()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialProfileUpdateOne) SetUpdatedAt(v time.Time) *CredentialProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CredentialProfileMutation object of the builder.
func (_u *CredentialProfileUpdateOne) Mutation() *CredentialProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the CredentialProfileUpdate builder.
func (_u *CredentialProfileUpdateOne) Where(ps ...predicate.CredentialProfile) *CredentialProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CredentialProfileUpdateOne) Select(field string, fields ...string) *CredentialProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CredentialProfile entity.
func (_u *CredentialProfileUpdateOne) Save(ctx context.Context) (*CredentialProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialProfileUpdateOne) SaveX(ctx context.Context) *CredentialProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CredentialProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := credentialprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CredentialProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := credentialprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CredentialProfile.name": %w`, err)}
		}
	}
	return nil
}

func (_u *CredentialProfileUpdateOne) sqlSave(ctx context.Context) (_node *CredentialProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credentialprofile.Table, credentialprofile.Columns, sqlgraph.NewFieldSpec(credentialprofile.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CredentialProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, credentialprofile.FieldID)
		for _, f := range fields {
			if !credentialprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != credentialprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(credentialprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(credentialprofile.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecLevel(); ok {
		_spec.SetField(credentialprofile.FieldSecLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Community(); ok {
		_spec.SetField(credentialprofile.FieldCommunity, field.TypeString, value)
	}
	if _u.mutation.CommunityCleared() {
		_spec.ClearField(credentialprofile.FieldCommunity, field.TypeString)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(credentialprofile.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(credentialprofile.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.AuthProtocol(); ok {
		_spec.SetField(credentialprofile.FieldAuthProtocol, field.TypeString, value)
	}
	if _u.mutation.AuthProtocolCleared() {
		_spec.ClearField(credentialprofile.FieldAuthProtocol, field.TypeString)
	}
	if value, ok := _u.mutation.AuthPassphrase(); ok {
		_spec.SetField(credentialprofile.FieldAuthPassphrase, field.TypeString, value)
	}
	if _u.mutation.AuthPassphraseCleared() {
		_spec.ClearField(credentialprofile.FieldAuthPassphrase, field.TypeString)
	}
	if value, ok := _u.mutation.PrivProtocol(); ok {
		_spec.SetField(credentialprofile.FieldPrivProtocol, field.TypeString, value)
	}
	if _u.mutation.PrivProtocolCleared() {
		_spec.ClearField(credentialprofile.FieldPrivProtocol, field.TypeString)
	}
	if value, ok := _u.mutation.PrivPassphrase(); ok {
		_spec.SetField(credentialprofile.FieldPrivPassphrase, field.TypeString, value)
	}
	if _u.mutation.PrivPassphraseCleared() {
		_spec.ClearField(credentialprofile.FieldPrivPassphrase, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credentialprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CredentialProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentialprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
