// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shjtmy/go_sh0jitmy_template/ent/credentialprofile"
)

// CredentialProfile is the model entity for the CredentialProfile schema.
type CredentialProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// SecLevel holds the value of the "sec_level" field.
	SecLevel string `json:"sec_level,omitempty"`
	// Community holds the value of the "community" field.
	Community string `json:"community,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// AuthProtocol holds the value of the "auth_protocol" field.
	AuthProtocol string `json:"auth_protocol,omitempty"`
	// AuthPassphrase holds the value of the "auth_passphrase" field.
	AuthPassphrase string `json:"-"`
	// PrivProtocol holds the value of the "priv_protocol" field.
	PrivProtocol string `json:"priv_protocol,omitempty"`
	// PrivPassphrase holds the value of the "priv_passphrase" field.
	PrivPassphrase string `json:"-"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CredentialProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case credentialprofile.FieldID, credentialprofile.FieldName, credentialprofile.FieldVersion, credentialprofile.FieldSecLevel, credentialprofile.FieldCommunity, credentialprofile.FieldUsername, credentialprofile.FieldAuthProtocol, credentialprofile.FieldAuthPassphrase, credentialprofile.FieldPrivProtocol, credentialprofile.FieldPrivPassphrase:
			values[i] = new(sql.NullString)
		case credentialprofile.FieldCreatedAt, credentialprofile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CredentialProfile fields.
func (_m *CredentialProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case credentialprofile.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case credentialprofile.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case credentialprofile.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case credentialprofile.FieldSecLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sec_level", values[i])
			} else if value.Valid {
				_m.SecLevel = value.String
			}
		case credentialprofile.FieldCommunity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field community", values[i])
			} else if value.Valid {
				_m.Community = value.String
			}
		case credentialprofile.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case credentialprofile.FieldAuthProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_protocol", values[i])
			} else if value.Valid {
				_m.AuthProtocol = value.String
			}
		case credentialprofile.FieldAuthPassphrase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_passphrase", values[i])
			} else if value.Valid {
				_m.AuthPassphrase = value.String
			}
		case credentialprofile.FieldPrivProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priv_protocol", values[i])
			} else if value.Valid {
				_m.PrivProtocol = value.String
			}
		case credentialprofile.FieldPrivPassphrase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priv_passphrase", values[i])
			} else if value.Valid {
				_m.PrivPassphrase = value.String
			}
		case credentialprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case credentialprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CredentialProfile.
// This includes values selected through modifiers, order, etc.
func (_m *CredentialProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CredentialProfile.
// Note that you need to call CredentialProfile.Unwrap() before calling this method if this CredentialProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CredentialProfile) Update() *CredentialProfileUpdateOne {
	return NewCredentialProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CredentialProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CredentialProfile) Unwrap() *CredentialProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CredentialProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CredentialProfile) String() string {
	var builder strings.Builder
	builder.WriteString("CredentialProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("sec_level=")
	builder.WriteString(_m.SecLevel)
	builder.WriteString(", ")
	builder.WriteString("community=")
	builder.WriteString(_m.Community)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("auth_protocol=")
	builder.WriteString(_m.AuthProtocol)
	builder.WriteString(", ")
	builder.WriteString("auth_passphrase=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("priv_protocol=")
	builder.WriteString(_m.PrivProtocol)
	builder.WriteString(", ")
	builder.WriteString("priv_passphrase=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CredentialProfiles is a parsable slice of CredentialProfile.
type CredentialProfiles []*CredentialProfile
