// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sh0jitmy/musubi/ent/job"
)

// JobCreate is the builder for creating a Job entity.
type JobCreate struct {
	config
	mutation *JobMutation
	hooks    []Hook
}

// SetScenarioID sets the "scenario_id" field.
func (_c *JobCreate) SetScenarioID(v string) *JobCreate {
	_c.mutation.SetScenarioID(v)
	return _c
}

// SetScenarioVersion sets the "scenario_version" field.
func (_c *JobCreate) SetScenarioVersion(v int) *JobCreate {
	_c.mutation.SetScenarioVersion(v)
	return _c
}

// SetNillableScenarioVersion sets the "scenario_version" field if the given value is not nil.
func (_c *JobCreate) SetNillableScenarioVersion(v *int) *JobCreate {
	if v != nil {
		_c.SetScenarioVersion(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *JobCreate) SetStatus(v string) *JobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *JobCreate) SetNillableStatus(v *string) *JobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDynamicInputs sets the "dynamic_inputs" field.
func (_c *JobCreate) SetDynamicInputs(v map[string]interface{}) *JobCreate {
	_c.mutation.SetDynamicInputs(v)
	return _c
}

// SetLockedTargets sets the "locked_targets" field.
func (_c *JobCreate) SetLockedTargets(v []string) *JobCreate {
	_c.mutation.SetLockedTargets(v)
	return _c
}

// SetTriggeredBy sets the "triggered_by" field.
func (_c *JobCreate) SetTriggeredBy(v string) *JobCreate {
	_c.mutation.SetTriggeredBy(v)
	return _c
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_c *JobCreate) SetNillableTriggeredBy(v *string) *JobCreate {
	if v != nil {
		_c.SetTriggeredBy(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *JobCreate) SetStartedAt(v time.Time) *JobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *JobCreate) SetNillableStartedAt(v *time.Time) *JobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *JobCreate) SetFinishedAt(v time.Time) *JobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *JobCreate) SetNillableFinishedAt(v *time.Time) *JobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *JobCreate) SetCreatedAt(v time.Time) *JobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *JobCreate) SetNillableCreatedAt(v *time.Time) *JobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *JobCreate) SetID(v string) *JobCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the JobMutation object of the builder.
func (_c *JobCreate) Mutation() *JobMutation {
	return _c.mutation
}

// Save creates the Job in the database.
func (_c *JobCreate) Save(ctx context.Context) (*Job, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JobCreate) SaveX(ctx context.Context) *Job {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *JobCreate) defaults() {
	if _, ok := _c.mutation.ScenarioVersion(); !ok {
		v := job.DefaultScenarioVersion
		_c.mutation.SetScenarioVersion(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := job.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TriggeredBy(); !ok {
		v := job.DefaultTriggeredBy
		_c.mutation.SetTriggeredBy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := job.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JobCreate) check() error {
	if _, ok := _c.mutation.ScenarioID(); !ok {
		return &ValidationError{Name: "scenario_id", err: errors.New(`ent: missing required field "Job.scenario_id"`)}
	}
	if v, ok := _c.mutation.ScenarioID(); ok {
		if err := job.ScenarioIDValidator(v); err != nil {
			return &ValidationError{Name: "scenario_id", err: fmt.Errorf(`ent: validator failed for field "Job.scenario_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScenarioVersion(); !ok {
		return &ValidationError{Name: "scenario_version", err: errors.New(`ent: missing required field "Job.scenario_version"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Job.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Job.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := job.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Job.id": %w`, err)}
		}
	}
	return nil
}

func (_c *JobCreate) sqlSave(ctx context.Context) (*Job, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Job.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JobCreate) createSpec() (*Job, *sqlgraph.CreateSpec) {
	var (
		_node = &Job{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(job.Table, sqlgraph.NewFieldSpec(job.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ScenarioID(); ok {
		_spec.SetField(job.FieldScenarioID, field.TypeString, value)
		_node.ScenarioID = value
	}
	if value, ok := _c.mutation.ScenarioVersion(); ok {
		_spec.SetField(job.FieldScenarioVersion, field.TypeInt, value)
		_node.ScenarioVersion = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DynamicInputs(); ok {
		_spec.SetField(job.FieldDynamicInputs, field.TypeJSON, value)
		_node.DynamicInputs = value
	}
	if value, ok := _c.mutation.LockedTargets(); ok {
		_spec.SetField(job.FieldLockedTargets, field.TypeJSON, value)
		_node.LockedTargets = value
	}
	if value, ok := _c.mutation.TriggeredBy(); ok {
		_spec.SetField(job.FieldTriggeredBy, field.TypeString, value)
		_node.TriggeredBy = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(job.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(job.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// JobCreateBulk is the builder for creating many Job entities in bulk.
type JobCreateBulk struct {
	config
	err      error
	builders []*JobCreate
}

// Save creates the Job entities in the database.
func (_c *JobCreateBulk) Save(ctx context.Context) ([]*Job, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Job, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JobCreateBulk) SaveX(ctx context.Context) []*Job {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
