// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/sh0jitmy/musubi/ent/job"
	"github.com/sh0jitmy/musubi/ent/predicate"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScenarioID sets the "scenario_id" field.
func (_u *JobUpdate) SetScenarioID(v string) *JobUpdate {
	_u.mutation.SetScenarioID(v)
	return _u
}

// SetNillableScenarioID sets the "scenario_id" field if the given value is not nil.
func (_u *JobUpdate) SetNillableScenarioID(v *string) *JobUpdate {
	if v != nil {
		_u.SetScenarioID(*v)
	}
	return _u
}

// SetScenarioVersion sets the "scenario_version" field.
func (_u *JobUpdate) SetScenarioVersion(v int) *JobUpdate {
	_u.mutation.ResetScenarioVersion()
	_u.mutation.SetScenarioVersion(v)
	return _u
}

// SetNillableScenarioVersion sets the "scenario_version" field if the given value is not nil.
func (_u *JobUpdate) SetNillableScenarioVersion(v *int) *JobUpdate {
	if v != nil {
		_u.SetScenarioVersion(*v)
	}
	return _u
}

// AddScenarioVersion adds value to the "scenario_version" field.
func (_u *JobUpdate) AddScenarioVersion(v int) *JobUpdate {
	_u.mutation.AddScenarioVersion(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdate) SetStatus(v string) *JobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdate) SetNillableStatus(v *string) *JobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDynamicInputs sets the "dynamic_inputs" field.
func (_u *JobUpdate) SetDynamicInputs(v map[string]interface{}) *JobUpdate {
	_u.mutation.SetDynamicInputs(v)
	return _u
}

// ClearDynamicInputs clears the value of the "dynamic_inputs" field.
func (_u *JobUpdate) ClearDynamicInputs() *JobUpdate {
	_u.mutation.ClearDynamicInputs()
	return _u
}

// SetLockedTargets sets the "locked_targets" field.
func (_u *JobUpdate) SetLockedTargets(v []string) *JobUpdate {
	_u.mutation.SetLockedTargets(v)
	return _u
}

// AppendLockedTargets appends value to the "locked_targets" field.
func (_u *JobUpdate) AppendLockedTargets(v []string) *JobUpdate {
	_u.mutation.AppendLockedTargets(v)
	return _u
}

// ClearLockedTargets clears the value of the "locked_targets" field.
func (_u *JobUpdate) ClearLockedTargets() *JobUpdate {
	_u.mutation.ClearLockedTargets()
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *JobUpdate) SetTriggeredBy(v string) *JobUpdate {
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *JobUpdate) SetNillableTriggeredBy(v *string) *JobUpdate {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// ClearTriggeredBy clears the value of the "triggered_by" field.
func (_u *JobUpdate) ClearTriggeredBy() *JobUpdate {
	_u.mutation.ClearTriggeredBy()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *JobUpdate) SetStartedAt(v time.Time) *JobUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableStartedAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *JobUpdate) ClearStartedAt() *JobUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobUpdate) SetFinishedAt(v time.Time) *JobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableFinishedAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *JobUpdate) ClearFinishedAt() *JobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdate) Mutation() *JobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdate) check() error {
	if v, ok := _u.mutation.ScenarioID(); ok {
		if err := job.ScenarioIDValidator(v); err != nil {
			return &ValidationError{Name: "scenario_id", err: fmt.Errorf(`ent: validator failed for field "Job.scenario_id": %w`, err)}
		}
	}
	return nil
}

func (_u *JobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScenarioID(); ok {
		_spec.SetField(job.FieldScenarioID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScenarioVersion(); ok {
		_spec.SetField(job.FieldScenarioVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScenarioVersion(); ok {
		_spec.AddField(job.FieldScenarioVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DynamicInputs(); ok {
		_spec.SetField(job.FieldDynamicInputs, field.TypeJSON, value)
	}
	if _u.mutation.DynamicInputsCleared() {
		_spec.ClearField(job.FieldDynamicInputs, field.TypeJSON)
	}
	if value, ok := _u.mutation.LockedTargets(); ok {
		_spec.SetField(job.FieldLockedTargets, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLockedTargets(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, job.FieldLockedTargets, value)
		})
	}
	if _u.mutation.LockedTargetsCleared() {
		_spec.ClearField(job.FieldLockedTargets, field.TypeJSON)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(job.FieldTriggeredBy, field.TypeString, value)
	}
	if _u.mutation.TriggeredByCleared() {
		_spec.ClearField(job.FieldTriggeredBy, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(job.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(job.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(job.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetScenarioID sets the "scenario_id" field.
func (_u *JobUpdateOne) SetScenarioID(v string) *JobUpdateOne {
	_u.mutation.SetScenarioID(v)
	return _u
}

// SetNillableScenarioID sets the "scenario_id" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableScenarioID(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetScenarioID(*v)
	}
	return _u
}

// SetScenarioVersion sets the "scenario_version" field.
func (_u *JobUpdateOne) SetScenarioVersion(v int) *JobUpdateOne {
	_u.mutation.ResetScenarioVersion()
	_u.mutation.SetScenarioVersion(v)
	return _u
}

// SetNillableScenarioVersion sets the "scenario_version" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableScenarioVersion(v *int) *JobUpdateOne {
	if v != nil {
		_u.SetScenarioVersion(*v)
	}
	return _u
}

// AddScenarioVersion adds value to the "scenario_version" field.
func (_u *JobUpdateOne) AddScenarioVersion(v int) *JobUpdateOne {
	_u.mutation.AddScenarioVersion(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdateOne) SetStatus(v string) *JobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableStatus(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDynamicInputs sets the "dynamic_inputs" field.
func (_u *JobUpdateOne) SetDynamicInputs(v map[string]interface{}) *JobUpdateOne {
	_u.mutation.SetDynamicInputs(v)
	return _u
}

// ClearDynamicInputs clears the value of the "dynamic_inputs" field.
func (_u *JobUpdateOne) ClearDynamicInputs() *JobUpdateOne {
	_u.mutation.ClearDynamicInputs()
	return _u
}

// SetLockedTargets sets the "locked_targets" field.
func (_u *JobUpdateOne) SetLockedTargets(v []string) *JobUpdateOne {
	_u.mutation.SetLockedTargets(v)
	return _u
}

// AppendLockedTargets appends value to the "locked_targets" field.
func (_u *JobUpdateOne) AppendLockedTargets(v []string) *JobUpdateOne {
	_u.mutation.AppendLockedTargets(v)
	return _u
}

// ClearLockedTargets clears the value of the "locked_targets" field.
func (_u *JobUpdateOne) ClearLockedTargets() *JobUpdateOne {
	_u.mutation.ClearLockedTargets()
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *JobUpdateOne) SetTriggeredBy(v string) *JobUpdateOne {
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableTriggeredBy(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// ClearTriggeredBy clears the value of the "triggered_by" field.
func (_u *JobUpdateOne) ClearTriggeredBy() *JobUpdateOne {
	_u.mutation.ClearTriggeredBy()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *JobUpdateOne) SetStartedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableStartedAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *JobUpdateOne) ClearStartedAt() *JobUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobUpdateOne) SetFinishedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableFinishedAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *JobUpdateOne) ClearFinishedAt() *JobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdateOne) Mutation() *JobMutation {
	return _u.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Job entity.
func (_u *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdateOne) check() error {
	if v, ok := _u.mutation.ScenarioID(); ok {
		if err := job.ScenarioIDValidator(v); err != nil {
			return &ValidationError{Name: "scenario_id", err: fmt.Errorf(`ent: validator failed for field "Job.scenario_id": %w`, err)}
		}
	}
	return nil
}

func (_u *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScenarioID(); ok {
		_spec.SetField(job.FieldScenarioID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScenarioVersion(); ok {
		_spec.SetField(job.FieldScenarioVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScenarioVersion(); ok {
		_spec.AddField(job.FieldScenarioVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DynamicInputs(); ok {
		_spec.SetField(job.FieldDynamicInputs, field.TypeJSON, value)
	}
	if _u.mutation.DynamicInputsCleared() {
		_spec.ClearField(job.FieldDynamicInputs, field.TypeJSON)
	}
	if value, ok := _u.mutation.LockedTargets(); ok {
		_spec.SetField(job.FieldLockedTargets, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLockedTargets(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, job.FieldLockedTargets, value)
		})
	}
	if _u.mutation.LockedTargetsCleared() {
		_spec.ClearField(job.FieldLockedTargets, field.TypeJSON)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(job.FieldTriggeredBy, field.TypeString, value)
	}
	if _u.mutation.TriggeredByCleared() {
		_spec.ClearField(job.FieldTriggeredBy, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(job.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(job.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(job.FieldFinishedAt, field.TypeTime)
	}
	_node = &Job{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
