// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shjtmy/go_sh0jitmy_template/ent/jobstep"
	"github.com/shjtmy/go_sh0jitmy_template/ent/predicate"
)

// JobStepUpdate is the builder for updating JobStep entities.
type JobStepUpdate struct {
	config
	hooks    []Hook
	mutation *JobStepMutation
}

// Where appends a list predicates to the JobStepUpdate builder.
func (_u *JobStepUpdate) Where(ps ...predicate.JobStep) *JobStepUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *JobStepUpdate) SetJobID(v string) *JobStepUpdate {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *JobStepUpdate) SetNillableJobID(v *string) *JobStepUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetStepID sets the "step_id" field.
func (_u *JobStepUpdate) SetStepID(v string) *JobStepUpdate {
	_u.mutation.SetStepID(v)
	return _u
}

// SetNillableStepID sets the "step_id" field if the given value is not nil.
func (_u *JobStepUpdate) SetNillableStepID(v *string) *JobStepUpdate {
	if v != nil {
		_u.SetStepID(*v)
	}
	return _u
}

// SetStepOrder sets the "step_order" field.
func (_u *JobStepUpdate) SetStepOrder(v int) *JobStepUpdate {
	_u.mutation.ResetStepOrder()
	_u.mutation.SetStepOrder(v)
	return _u
}

// SetNillableStepOrder sets the "step_order" field if the given value is not nil.
func (_u *JobStepUpdate) SetNillableStepOrder(v *int) *JobStepUpdate {
	if v != nil {
		_u.SetStepOrder(*v)
	}
	return _u
}

// AddStepOrder adds value to the "step_order" field.
func (_u *JobStepUpdate) AddStepOrder(v int) *JobStepUpdate {
	_u.mutation.AddStepOrder(v)
	return _u
}

// SetStepType sets the "step_type" field.
func (_u *JobStepUpdate) SetStepType(v string) *JobStepUpdate {
	_u.mutation.SetStepType(v)
	return _u
}

// SetNillableStepType sets the "step_type" field if the given value is not nil.
func (_u *JobStepUpdate) SetNillableStepType(v *string) *JobStepUpdate {
	if v != nil {
		_u.SetStepType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobStepUpdate) SetStatus(v string) *JobStepUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobStepUpdate) SetNillableStatus(v *string) *JobStepUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResultOutput sets the "result_output" field.
func (_u *JobStepUpdate) SetResultOutput(v map[string]interface{}) *JobStepUpdate {
	_u.mutation.SetResultOutput(v)
	return _u
}

// ClearResultOutput clears the value of the "result_output" field.
func (_u *JobStepUpdate) ClearResultOutput() *JobStepUpdate {
	_u.mutation.ClearResultOutput()
	return _u
}

// SetError sets the "error" field.
func (_u *JobStepUpdate) SetError(v string) *JobStepUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *JobStepUpdate) SetNillableError(v *string) *JobStepUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *JobStepUpdate) ClearError() *JobStepUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *JobStepUpdate) SetExecutedAt(v time.Time) *JobStepUpdate {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *JobStepUpdate) SetNillableExecutedAt(v *time.Time) *JobStepUpdate {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// Mutation returns the JobStepMutation object of the builder.
func (_u *JobStepUpdate) Mutation() *JobStepMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobStepUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobStepUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobStepUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobStepUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobStepUpdate) check() error {
	if v, ok := _u.mutation.JobID(); ok {
		if err := jobstep.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "JobStep.job_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StepID(); ok {
		if err := jobstep.StepIDValidator(v); err != nil {
			return &ValidationError{Name: "step_id", err: fmt.Errorf(`ent: validator failed for field "JobStep.step_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StepType(); ok {
		if err := jobstep.StepTypeValidator(v); err != nil {
			return &ValidationError{Name: "step_type", err: fmt.Errorf(`ent: validator failed for field "JobStep.step_type": %w`, err)}
		}
	}
	return nil
}

func (_u *JobStepUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(jobstep.Table, jobstep.Columns, sqlgraph.NewFieldSpec(jobstep.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(jobstep.FieldJobID, field.TypeString, value)
	}
	if value, ok := _u.mutation.StepID(); ok {
		_spec.SetField(jobstep.FieldStepID, field.TypeString, value)
	}
	if value, ok := _u.mutation.StepOrder(); ok {
		_spec.SetField(jobstep.FieldStepOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStepOrder(); ok {
		_spec.AddField(jobstep.FieldStepOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StepType(); ok {
		_spec.SetField(jobstep.FieldStepType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(jobstep.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultOutput(); ok {
		_spec.SetField(jobstep.FieldResultOutput, field.TypeJSON, value)
	}
	if _u.mutation.ResultOutputCleared() {
		_spec.ClearField(jobstep.FieldResultOutput, field.TypeJSON)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(jobstep.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(jobstep.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(jobstep.FieldExecutedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobstep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobStepUpdateOne is the builder for updating a single JobStep entity.
type JobStepUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobStepMutation
}

// SetJobID sets the "job_id" field.
func (_u *JobStepUpdateOne) SetJobID(v string) *JobStepUpdateOne {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *JobStepUpdateOne) SetNillableJobID(v *string) *JobStepUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetStepID sets the "step_id" field.
func (_u *JobStepUpdateOne) SetStepID(v string) *JobStepUpdateOne {
	_u.mutation.SetStepID(v)
	return _u
}

// SetNillableStepID sets the "step_id" field if the given value is not nil.
func (_u *JobStepUpdateOne) SetNillableStepID(v *string) *JobStepUpdateOne {
	if v != nil {
		_u.SetStepID(*v)
	}
	return _u
}

// SetStepOrder sets the "step_order" field.
func (_u *JobStepUpdateOne) SetStepOrder(v int) *JobStepUpdateOne {
	_u.mutation.ResetStepOrder()
	_u.mutation.SetStepOrder(v)
	return _u
}

// SetNillableStepOrder sets the "step_order" field if the given value is not nil.
func (_u *JobStepUpdateOne) SetNillableStepOrder(v *int) *JobStepUpdateOne {
	if v != nil {
		_u.SetStepOrder(*v)
	}
	return _u
}

// AddStepOrder adds value to the "step_order" field.
func (_u *JobStepUpdateOne) AddStepOrder(v int) *JobStepUpdateOne {
	_u.mutation.AddStepOrder(v)
	return _u
}

// SetStepType sets the "step_type" field.
func (_u *JobStepUpdateOne) SetStepType(v string) *JobStepUpdateOne {
	_u.mutation.SetStepType(v)
	return _u
}

// SetNillableStepType sets the "step_type" field if the given value is not nil.
func (_u *JobStepUpdateOne) SetNillableStepType(v *string) *JobStepUpdateOne {
	if v != nil {
		_u.SetStepType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobStepUpdateOne) SetStatus(v string) *JobStepUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobStepUpdateOne) SetNillableStatus(v *string) *JobStepUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResultOutput sets the "result_output" field.
func (_u *JobStepUpdateOne) SetResultOutput(v map[string]interface{}) *JobStepUpdateOne {
	_u.mutation.SetResultOutput(v)
	return _u
}

// ClearResultOutput clears the value of the "result_output" field.
func (_u *JobStepUpdateOne) ClearResultOutput() *JobStepUpdateOne {
	_u.mutation.ClearResultOutput()
	return _u
}

// SetError sets the "error" field.
func (_u *JobStepUpdateOne) SetError(v string) *JobStepUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *JobStepUpdateOne) SetNillableError(v *string) *JobStepUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *JobStepUpdateOne) ClearError() *JobStepUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *JobStepUpdateOne) SetExecutedAt(v time.Time) *JobStepUpdateOne {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *JobStepUpdateOne) SetNillableExecutedAt(v *time.Time) *JobStepUpdateOne {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// Mutation returns the JobStepMutation object of the builder.
func (_u *JobStepUpdateOne) Mutation() *JobStepMutation {
	return _u.mutation
}

// Where appends a list predicates to the JobStepUpdate builder.
func (_u *JobStepUpdateOne) Where(ps ...predicate.JobStep) *JobStepUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobStepUpdateOne) Select(field string, fields ...string) *JobStepUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated JobStep entity.
func (_u *JobStepUpdateOne) Save(ctx context.Context) (*JobStep, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobStepUpdateOne) SaveX(ctx context.Context) *JobStep {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobStepUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobStepUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobStepUpdateOne) check() error {
	if v, ok := _u.mutation.JobID(); ok {
		if err := jobstep.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "JobStep.job_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StepID(); ok {
		if err := jobstep.StepIDValidator(v); err != nil {
			return &ValidationError{Name: "step_id", err: fmt.Errorf(`ent: validator failed for field "JobStep.step_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StepType(); ok {
		if err := jobstep.StepTypeValidator(v); err != nil {
			return &ValidationError{Name: "step_type", err: fmt.Errorf(`ent: validator failed for field "JobStep.step_type": %w`, err)}
		}
	}
	return nil
}

func (_u *JobStepUpdateOne) sqlSave(ctx context.Context) (_node *JobStep, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(jobstep.Table, jobstep.Columns, sqlgraph.NewFieldSpec(jobstep.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JobStep.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobstep.FieldID)
		for _, f := range fields {
			if !jobstep.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != jobstep.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(jobstep.FieldJobID, field.TypeString, value)
	}
	if value, ok := _u.mutation.StepID(); ok {
		_spec.SetField(jobstep.FieldStepID, field.TypeString, value)
	}
	if value, ok := _u.mutation.StepOrder(); ok {
		_spec.SetField(jobstep.FieldStepOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStepOrder(); ok {
		_spec.AddField(jobstep.FieldStepOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StepType(); ok {
		_spec.SetField(jobstep.FieldStepType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(jobstep.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultOutput(); ok {
		_spec.SetField(jobstep.FieldResultOutput, field.TypeJSON, value)
	}
	if _u.mutation.ResultOutputCleared() {
		_spec.ClearField(jobstep.FieldResultOutput, field.TypeJSON)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(jobstep.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(jobstep.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(jobstep.FieldExecutedAt, field.TypeTime, value)
	}
	_node = &JobStep{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobstep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
