// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sh0jitmy/musubi/ent/jobstep"
)

// JobStep is the model entity for the JobStep schema.
type JobStep struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID string `json:"job_id,omitempty"`
	// StepID holds the value of the "step_id" field.
	StepID string `json:"step_id,omitempty"`
	// StepOrder holds the value of the "step_order" field.
	StepOrder int `json:"step_order,omitempty"`
	// StepType holds the value of the "step_type" field.
	StepType string `json:"step_type,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ResultOutput holds the value of the "result_output" field.
	ResultOutput map[string]interface{} `json:"result_output,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// ExecutedAt holds the value of the "executed_at" field.
	ExecutedAt   time.Time `json:"executed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JobStep) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jobstep.FieldResultOutput:
			values[i] = new([]byte)
		case jobstep.FieldStepOrder:
			values[i] = new(sql.NullInt64)
		case jobstep.FieldID, jobstep.FieldJobID, jobstep.FieldStepID, jobstep.FieldStepType, jobstep.FieldStatus, jobstep.FieldError:
			values[i] = new(sql.NullString)
		case jobstep.FieldExecutedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JobStep fields.
func (_m *JobStep) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jobstep.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case jobstep.FieldJobID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.String
			}
		case jobstep.FieldStepID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field step_id", values[i])
			} else if value.Valid {
				_m.StepID = value.String
			}
		case jobstep.FieldStepOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field step_order", values[i])
			} else if value.Valid {
				_m.StepOrder = int(value.Int64)
			}
		case jobstep.FieldStepType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field step_type", values[i])
			} else if value.Valid {
				_m.StepType = value.String
			}
		case jobstep.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case jobstep.FieldResultOutput:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result_output", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResultOutput); err != nil {
					return fmt.Errorf("unmarshal field result_output: %w", err)
				}
			}
		case jobstep.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case jobstep.FieldExecutedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field executed_at", values[i])
			} else if value.Valid {
				_m.ExecutedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JobStep.
// This includes values selected through modifiers, order, etc.
func (_m *JobStep) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this JobStep.
// Note that you need to call JobStep.Unwrap() before calling this method if this JobStep
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *JobStep) Update() *JobStepUpdateOne {
	return NewJobStepClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the JobStep entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *JobStep) Unwrap() *JobStep {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: JobStep is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *JobStep) String() string {
	var builder strings.Builder
	builder.WriteString("JobStep(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("job_id=")
	builder.WriteString(_m.JobID)
	builder.WriteString(", ")
	builder.WriteString("step_id=")
	builder.WriteString(_m.StepID)
	builder.WriteString(", ")
	builder.WriteString("step_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.StepOrder))
	builder.WriteString(", ")
	builder.WriteString("step_type=")
	builder.WriteString(_m.StepType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("result_output=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultOutput))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("executed_at=")
	builder.WriteString(_m.ExecutedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// JobSteps is a parsable slice of JobStep.
type JobSteps []*JobStep
