// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shjtmy/go_sh0jitmy_template/ent/predicate"
	"github.com/shjtmy/go_sh0jitmy_template/ent/scenario"
)

// ScenarioUpdate is the builder for updating Scenario entities.
type ScenarioUpdate struct {
	config
	hooks    []Hook
	mutation *ScenarioMutation
}

// Where appends a list predicates to the ScenarioUpdate builder.
func (_u *ScenarioUpdate) Where(ps ...predicate.Scenario) *ScenarioUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ScenarioUpdate) SetName(v string) *ScenarioUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScenarioUpdate) SetNillableName(v *string) *ScenarioUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScenarioUpdate) SetDescription(v string) *ScenarioUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScenarioUpdate) SetNillableDescription(v *string) *ScenarioUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ScenarioUpdate) ClearDescription() *ScenarioUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCurrentVersion sets the "current_version" field.
func (_u *ScenarioUpdate) SetCurrentVersion(v int) *ScenarioUpdate {
	_u.mutation.ResetCurrentVersion()
	_u.mutation.SetCurrentVersion(v)
	return _u
}

// SetNillableCurrentVersion sets the "current_version" field if the given value is not nil.
func (_u *ScenarioUpdate) SetNillableCurrentVersion(v *int) *ScenarioUpdate {
	if v != nil {
		_u.SetCurrentVersion(*v)
	}
	return _u
}

// AddCurrentVersion adds value to the "current_version" field.
func (_u *ScenarioUpdate) AddCurrentVersion(v int) *ScenarioUpdate {
	_u.mutation.AddCurrentVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScenarioUpdate) SetUpdatedAt(v time.Time) *ScenarioUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ScenarioMutation object of the builder.
func (_u *ScenarioUpdate) Mutation() *ScenarioMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScenarioUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScenarioUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScenarioUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScenarioUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScenarioUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scenario.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScenarioUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := scenario.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Scenario.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ScenarioUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scenario.Table, scenario.Columns, sqlgraph.NewFieldSpec(scenario.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(scenario.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(scenario.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(scenario.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CurrentVersion(); ok {
		_spec.SetField(scenario.FieldCurrentVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentVersion(); ok {
		_spec.AddField(scenario.FieldCurrentVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scenario.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scenario.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScenarioUpdateOne is the builder for updating a single Scenario entity.
type ScenarioUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScenarioMutation
}

// SetName sets the "name" field.
func (_u *ScenarioUpdateOne) SetName(v string) *ScenarioUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScenarioUpdateOne) SetNillableName(v *string) *ScenarioUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScenarioUpdateOne) SetDescription(v string) *ScenarioUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScenarioUpdateOne) SetNillableDescription(v *string) *ScenarioUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ScenarioUpdateOne) ClearDescription() *ScenarioUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCurrentVersion sets the "current_version" field.
func (_u *ScenarioUpdateOne) SetCurrentVersion(v int) *ScenarioUpdateOne {
	_u.mutation.ResetCurrentVersion()
	_u.mutation.SetCurrentVersion(v)
	return _u
}

// SetNillableCurrentVersion sets the "current_version" field if the given value is not nil.
func (_u *ScenarioUpdateOne) SetNillableCurrentVersion(v *int) *ScenarioUpdateOne {
	if v != nil {
		_u.SetCurrentVersion(*v)
	}
	return _u
}

// AddCurrentVersion adds value to the "current_version" field.
func (_u *ScenarioUpdateOne) AddCurrentVersion(v int) *ScenarioUpdateOne {
	_u.mutation.AddCurrentVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScenarioUpdateOne) SetUpdatedAt(v time.Time) *ScenarioUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ScenarioMutation object of the builder.
func (_u *ScenarioUpdateOne) Mutation() *ScenarioMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScenarioUpdate builder.
func (_u *ScenarioUpdateOne) Where(ps ...predicate.Scenario) *ScenarioUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScenarioUpdateOne) Select(field string, fields ...string) *ScenarioUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Scenario entity.
func (_u *ScenarioUpdateOne) Save(ctx context.Context) (*Scenario, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScenarioUpdateOne) SaveX(ctx context.Context) *Scenario {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScenarioUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScenarioUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScenarioUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scenario.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScenarioUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := scenario.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Scenario.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ScenarioUpdateOne) sqlSave(ctx context.Context) (_node *Scenario, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scenario.Table, scenario.Columns, sqlgraph.NewFieldSpec(scenario.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Scenario.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scenario.FieldID)
		for _, f := range fields {
			if !scenario.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scenario.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(scenario.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(scenario.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(scenario.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CurrentVersion(); ok {
		_spec.SetField(scenario.FieldCurrentVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentVersion(); ok {
		_spec.AddField(scenario.FieldCurrentVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scenario.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Scenario{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scenario.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
