// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/sh0jitmy/musubi/ent/predicate"
	"github.com/sh0jitmy/musubi/ent/scenarioversion"
)

// ScenarioVersionUpdate is the builder for updating ScenarioVersion entities.
type ScenarioVersionUpdate struct {
	config
	hooks    []Hook
	mutation *ScenarioVersionMutation
}

// Where appends a list predicates to the ScenarioVersionUpdate builder.
func (_u *ScenarioVersionUpdate) Where(ps ...predicate.ScenarioVersion) *ScenarioVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScenarioID sets the "scenario_id" field.
func (_u *ScenarioVersionUpdate) SetScenarioID(v string) *ScenarioVersionUpdate {
	_u.mutation.SetScenarioID(v)
	return _u
}

// SetNillableScenarioID sets the "scenario_id" field if the given value is not nil.
func (_u *ScenarioVersionUpdate) SetNillableScenarioID(v *string) *ScenarioVersionUpdate {
	if v != nil {
		_u.SetScenarioID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ScenarioVersionUpdate) SetVersion(v int) *ScenarioVersionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ScenarioVersionUpdate) SetNillableVersion(v *int) *ScenarioVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ScenarioVersionUpdate) AddVersion(v int) *ScenarioVersionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetDslYaml sets the "dsl_yaml" field.
func (_u *ScenarioVersionUpdate) SetDslYaml(v string) *ScenarioVersionUpdate {
	_u.mutation.SetDslYaml(v)
	return _u
}

// SetNillableDslYaml sets the "dsl_yaml" field if the given value is not nil.
func (_u *ScenarioVersionUpdate) SetNillableDslYaml(v *string) *ScenarioVersionUpdate {
	if v != nil {
		_u.SetDslYaml(*v)
	}
	return _u
}

// SetInputsSchema sets the "inputs_schema" field.
func (_u *ScenarioVersionUpdate) SetInputsSchema(v map[string]interface{}) *ScenarioVersionUpdate {
	_u.mutation.SetInputsSchema(v)
	return _u
}

// ClearInputsSchema clears the value of the "inputs_schema" field.
func (_u *ScenarioVersionUpdate) ClearInputsSchema() *ScenarioVersionUpdate {
	_u.mutation.ClearInputsSchema()
	return _u
}

// SetTargetNames sets the "target_names" field.
func (_u *ScenarioVersionUpdate) SetTargetNames(v []string) *ScenarioVersionUpdate {
	_u.mutation.SetTargetNames(v)
	return _u
}

// AppendTargetNames appends value to the "target_names" field.
func (_u *ScenarioVersionUpdate) AppendTargetNames(v []string) *ScenarioVersionUpdate {
	_u.mutation.AppendTargetNames(v)
	return _u
}

// ClearTargetNames clears the value of the "target_names" field.
func (_u *ScenarioVersionUpdate) ClearTargetNames() *ScenarioVersionUpdate {
	_u.mutation.ClearTargetNames()
	return _u
}

// Mutation returns the ScenarioVersionMutation object of the builder.
func (_u *ScenarioVersionUpdate) Mutation() *ScenarioVersionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScenarioVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScenarioVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScenarioVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScenarioVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScenarioVersionUpdate) check() error {
	if v, ok := _u.mutation.ScenarioID(); ok {
		if err := scenarioversion.ScenarioIDValidator(v); err != nil {
			return &ValidationError{Name: "scenario_id", err: fmt.Errorf(`ent: validator failed for field "ScenarioVersion.scenario_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DslYaml(); ok {
		if err := scenarioversion.DslYamlValidator(v); err != nil {
			return &ValidationError{Name: "dsl_yaml", err: fmt.Errorf(`ent: validator failed for field "ScenarioVersion.dsl_yaml": %w`, err)}
		}
	}
	return nil
}

func (_u *ScenarioVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scenarioversion.Table, scenarioversion.Columns, sqlgraph.NewFieldSpec(scenarioversion.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScenarioID(); ok {
		_spec.SetField(scenarioversion.FieldScenarioID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(scenarioversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(scenarioversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DslYaml(); ok {
		_spec.SetField(scenarioversion.FieldDslYaml, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputsSchema(); ok {
		_spec.SetField(scenarioversion.FieldInputsSchema, field.TypeJSON, value)
	}
	if _u.mutation.InputsSchemaCleared() {
		_spec.ClearField(scenarioversion.FieldInputsSchema, field.TypeJSON)
	}
	if value, ok := _u.mutation.TargetNames(); ok {
		_spec.SetField(scenarioversion.FieldTargetNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTargetNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, scenarioversion.FieldTargetNames, value)
		})
	}
	if _u.mutation.TargetNamesCleared() {
		_spec.ClearField(scenarioversion.FieldTargetNames, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scenarioversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScenarioVersionUpdateOne is the builder for updating a single ScenarioVersion entity.
type ScenarioVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScenarioVersionMutation
}

// SetScenarioID sets the "scenario_id" field.
func (_u *ScenarioVersionUpdateOne) SetScenarioID(v string) *ScenarioVersionUpdateOne {
	_u.mutation.SetScenarioID(v)
	return _u
}

// SetNillableScenarioID sets the "scenario_id" field if the given value is not nil.
func (_u *ScenarioVersionUpdateOne) SetNillableScenarioID(v *string) *ScenarioVersionUpdateOne {
	if v != nil {
		_u.SetScenarioID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ScenarioVersionUpdateOne) SetVersion(v int) *ScenarioVersionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ScenarioVersionUpdateOne) SetNillableVersion(v *int) *ScenarioVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ScenarioVersionUpdateOne) AddVersion(v int) *ScenarioVersionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetDslYaml sets the "dsl_yaml" field.
func (_u *ScenarioVersionUpdateOne) SetDslYaml(v string) *ScenarioVersionUpdateOne {
	_u.mutation.SetDslYaml(v)
	return _u
}

// SetNillableDslYaml sets the "dsl_yaml" field if the given value is not nil.
func (_u *ScenarioVersionUpdateOne) SetNillableDslYaml(v *string) *ScenarioVersionUpdateOne {
	if v != nil {
		_u.SetDslYaml(*v)
	}
	return _u
}

// SetInputsSchema sets the "inputs_schema" field.
func (_u *ScenarioVersionUpdateOne) SetInputsSchema(v map[string]interface{}) *ScenarioVersionUpdateOne {
	_u.mutation.SetInputsSchema(v)
	return _u
}

// ClearInputsSchema clears the value of the "inputs_schema" field.
func (_u *ScenarioVersionUpdateOne) ClearInputsSchema() *ScenarioVersionUpdateOne {
	_u.mutation.ClearInputsSchema()
	return _u
}

// SetTargetNames sets the "target_names" field.
func (_u *ScenarioVersionUpdateOne) SetTargetNames(v []string) *ScenarioVersionUpdateOne {
	_u.mutation.SetTargetNames(v)
	return _u
}

// AppendTargetNames appends value to the "target_names" field.
func (_u *ScenarioVersionUpdateOne) AppendTargetNames(v []string) *ScenarioVersionUpdateOne {
	_u.mutation.AppendTargetNames(v)
	return _u
}

// ClearTargetNames clears the value of the "target_names" field.
func (_u *ScenarioVersionUpdateOne) ClearTargetNames() *ScenarioVersionUpdateOne {
	_u.mutation.ClearTargetNames()
	return _u
}

// Mutation returns the ScenarioVersionMutation object of the builder.
func (_u *ScenarioVersionUpdateOne) Mutation() *ScenarioVersionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScenarioVersionUpdate builder.
func (_u *ScenarioVersionUpdateOne) Where(ps ...predicate.ScenarioVersion) *ScenarioVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScenarioVersionUpdateOne) Select(field string, fields ...string) *ScenarioVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScenarioVersion entity.
func (_u *ScenarioVersionUpdateOne) Save(ctx context.Context) (*ScenarioVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScenarioVersionUpdateOne) SaveX(ctx context.Context) *ScenarioVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScenarioVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScenarioVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScenarioVersionUpdateOne) check() error {
	if v, ok := _u.mutation.ScenarioID(); ok {
		if err := scenarioversion.ScenarioIDValidator(v); err != nil {
			return &ValidationError{Name: "scenario_id", err: fmt.Errorf(`ent: validator failed for field "ScenarioVersion.scenario_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DslYaml(); ok {
		if err := scenarioversion.DslYamlValidator(v); err != nil {
			return &ValidationError{Name: "dsl_yaml", err: fmt.Errorf(`ent: validator failed for field "ScenarioVersion.dsl_yaml": %w`, err)}
		}
	}
	return nil
}

func (_u *ScenarioVersionUpdateOne) sqlSave(ctx context.Context) (_node *ScenarioVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scenarioversion.Table, scenarioversion.Columns, sqlgraph.NewFieldSpec(scenarioversion.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScenarioVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scenarioversion.FieldID)
		for _, f := range fields {
			if !scenarioversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scenarioversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScenarioID(); ok {
		_spec.SetField(scenarioversion.FieldScenarioID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(scenarioversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(scenarioversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DslYaml(); ok {
		_spec.SetField(scenarioversion.FieldDslYaml, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputsSchema(); ok {
		_spec.SetField(scenarioversion.FieldInputsSchema, field.TypeJSON, value)
	}
	if _u.mutation.InputsSchemaCleared() {
		_spec.ClearField(scenarioversion.FieldInputsSchema, field.TypeJSON)
	}
	if value, ok := _u.mutation.TargetNames(); ok {
		_spec.SetField(scenarioversion.FieldTargetNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTargetNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, scenarioversion.FieldTargetNames, value)
		})
	}
	if _u.mutation.TargetNamesCleared() {
		_spec.ClearField(scenarioversion.FieldTargetNames, field.TypeJSON)
	}
	_node = &ScenarioVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scenarioversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
