// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sh0jitmy/musubi/ent/predicate"
	"github.com/sh0jitmy/musubi/ent/scenarioversion"
)

// ScenarioVersionDelete is the builder for deleting a ScenarioVersion entity.
type ScenarioVersionDelete struct {
	config
	hooks    []Hook
	mutation *ScenarioVersionMutation
}

// Where appends a list predicates to the ScenarioVersionDelete builder.
func (_d *ScenarioVersionDelete) Where(ps ...predicate.ScenarioVersion) *ScenarioVersionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ScenarioVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ScenarioVersionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ScenarioVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(scenarioversion.Table, sqlgraph.NewFieldSpec(scenarioversion.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ScenarioVersionDeleteOne is the builder for deleting a single ScenarioVersion entity.
type ScenarioVersionDeleteOne struct {
	_d *ScenarioVersionDelete
}

// Where appends a list predicates to the ScenarioVersionDelete builder.
func (_d *ScenarioVersionDeleteOne) Where(ps ...predicate.ScenarioVersion) *ScenarioVersionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ScenarioVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{scenarioversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ScenarioVersionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
