// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sh0jitmy/musubi/ent/scenarioversion"
)

// ScenarioVersion is the model entity for the ScenarioVersion schema.
type ScenarioVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ScenarioID holds the value of the "scenario_id" field.
	ScenarioID string `json:"scenario_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// DslYaml holds the value of the "dsl_yaml" field.
	DslYaml string `json:"dsl_yaml,omitempty"`
	// InputsSchema holds the value of the "inputs_schema" field.
	InputsSchema map[string]interface{} `json:"inputs_schema,omitempty"`
	// TargetNames holds the value of the "target_names" field.
	TargetNames []string `json:"target_names,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScenarioVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scenarioversion.FieldInputsSchema, scenarioversion.FieldTargetNames:
			values[i] = new([]byte)
		case scenarioversion.FieldVersion:
			values[i] = new(sql.NullInt64)
		case scenarioversion.FieldID, scenarioversion.FieldScenarioID, scenarioversion.FieldDslYaml:
			values[i] = new(sql.NullString)
		case scenarioversion.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScenarioVersion fields.
func (_m *ScenarioVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scenarioversion.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case scenarioversion.FieldScenarioID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scenario_id", values[i])
			} else if value.Valid {
				_m.ScenarioID = value.String
			}
		case scenarioversion.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case scenarioversion.FieldDslYaml:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dsl_yaml", values[i])
			} else if value.Valid {
				_m.DslYaml = value.String
			}
		case scenarioversion.FieldInputsSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field inputs_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.InputsSchema); err != nil {
					return fmt.Errorf("unmarshal field inputs_schema: %w", err)
				}
			}
		case scenarioversion.FieldTargetNames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field target_names", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TargetNames); err != nil {
					return fmt.Errorf("unmarshal field target_names: %w", err)
				}
			}
		case scenarioversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScenarioVersion.
// This includes values selected through modifiers, order, etc.
func (_m *ScenarioVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ScenarioVersion.
// Note that you need to call ScenarioVersion.Unwrap() before calling this method if this ScenarioVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScenarioVersion) Update() *ScenarioVersionUpdateOne {
	return NewScenarioVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScenarioVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScenarioVersion) Unwrap() *ScenarioVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScenarioVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScenarioVersion) String() string {
	var builder strings.Builder
	builder.WriteString("ScenarioVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("scenario_id=")
	builder.WriteString(_m.ScenarioID)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("dsl_yaml=")
	builder.WriteString(_m.DslYaml)
	builder.WriteString(", ")
	builder.WriteString("inputs_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputsSchema))
	builder.WriteString(", ")
	builder.WriteString("target_names=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetNames))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ScenarioVersions is a parsable slice of ScenarioVersion.
type ScenarioVersions []*ScenarioVersion
