// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sh0jitmy/musubi/ent/scenarioversion"
)

// ScenarioVersionCreate is the builder for creating a ScenarioVersion entity.
type ScenarioVersionCreate struct {
	config
	mutation *ScenarioVersionMutation
	hooks    []Hook
}

// SetScenarioID sets the "scenario_id" field.
func (_c *ScenarioVersionCreate) SetScenarioID(v string) *ScenarioVersionCreate {
	_c.mutation.SetScenarioID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ScenarioVersionCreate) SetVersion(v int) *ScenarioVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ScenarioVersionCreate) SetNillableVersion(v *int) *ScenarioVersionCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetDslYaml sets the "dsl_yaml" field.
func (_c *ScenarioVersionCreate) SetDslYaml(v string) *ScenarioVersionCreate {
	_c.mutation.SetDslYaml(v)
	return _c
}

// SetInputsSchema sets the "inputs_schema" field.
func (_c *ScenarioVersionCreate) SetInputsSchema(v map[string]interface{}) *ScenarioVersionCreate {
	_c.mutation.SetInputsSchema(v)
	return _c
}

// SetTargetNames sets the "target_names" field.
func (_c *ScenarioVersionCreate) SetTargetNames(v []string) *ScenarioVersionCreate {
	_c.mutation.SetTargetNames(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ScenarioVersionCreate) SetCreatedAt(v time.Time) *ScenarioVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ScenarioVersionCreate) SetNillableCreatedAt(v *time.Time) *ScenarioVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScenarioVersionCreate) SetID(v string) *ScenarioVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ScenarioVersionMutation object of the builder.
func (_c *ScenarioVersionCreate) Mutation() *ScenarioVersionMutation {
	return _c.mutation
}

// Save creates the ScenarioVersion in the database.
func (_c *ScenarioVersionCreate) Save(ctx context.Context) (*ScenarioVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScenarioVersionCreate) SaveX(ctx context.Context) *ScenarioVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScenarioVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScenarioVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScenarioVersionCreate) defaults() {
	if _, ok := _c.mutation.Version(); !ok {
		v := scenarioversion.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := scenarioversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScenarioVersionCreate) check() error {
	if _, ok := _c.mutation.ScenarioID(); !ok {
		return &ValidationError{Name: "scenario_id", err: errors.New(`ent: missing required field "ScenarioVersion.scenario_id"`)}
	}
	if v, ok := _c.mutation.ScenarioID(); ok {
		if err := scenarioversion.ScenarioIDValidator(v); err != nil {
			return &ValidationError{Name: "scenario_id", err: fmt.Errorf(`ent: validator failed for field "ScenarioVersion.scenario_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ScenarioVersion.version"`)}
	}
	if _, ok := _c.mutation.DslYaml(); !ok {
		return &ValidationError{Name: "dsl_yaml", err: errors.New(`ent: missing required field "ScenarioVersion.dsl_yaml"`)}
	}
	if v, ok := _c.mutation.DslYaml(); ok {
		if err := scenarioversion.DslYamlValidator(v); err != nil {
			return &ValidationError{Name: "dsl_yaml", err: fmt.Errorf(`ent: validator failed for field "ScenarioVersion.dsl_yaml": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ScenarioVersion.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := scenarioversion.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ScenarioVersion.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ScenarioVersionCreate) sqlSave(ctx context.Context) (*ScenarioVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ScenarioVersion.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScenarioVersionCreate) createSpec() (*ScenarioVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &ScenarioVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(scenarioversion.Table, sqlgraph.NewFieldSpec(scenarioversion.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ScenarioID(); ok {
		_spec.SetField(scenarioversion.FieldScenarioID, field.TypeString, value)
		_node.ScenarioID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(scenarioversion.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.DslYaml(); ok {
		_spec.SetField(scenarioversion.FieldDslYaml, field.TypeString, value)
		_node.DslYaml = value
	}
	if value, ok := _c.mutation.InputsSchema(); ok {
		_spec.SetField(scenarioversion.FieldInputsSchema, field.TypeJSON, value)
		_node.InputsSchema = value
	}
	if value, ok := _c.mutation.TargetNames(); ok {
		_spec.SetField(scenarioversion.FieldTargetNames, field.TypeJSON, value)
		_node.TargetNames = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(scenarioversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ScenarioVersionCreateBulk is the builder for creating many ScenarioVersion entities in bulk.
type ScenarioVersionCreateBulk struct {
	config
	err      error
	builders []*ScenarioVersionCreate
}

// Save creates the ScenarioVersion entities in the database.
func (_c *ScenarioVersionCreateBulk) Save(ctx context.Context) ([]*ScenarioVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScenarioVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScenarioVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScenarioVersionCreateBulk) SaveX(ctx context.Context) []*ScenarioVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScenarioVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScenarioVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
