// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shjtmy/go_sh0jitmy_template/ent/statetransitionlog"
)

// StateTransitionLogCreate is the builder for creating a StateTransitionLog entity.
type StateTransitionLogCreate struct {
	config
	mutation *StateTransitionLogMutation
	hooks    []Hook
}

// SetTarget sets the "target" field.
func (_c *StateTransitionLogCreate) SetTarget(v string) *StateTransitionLogCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetStateKey sets the "state_key" field.
func (_c *StateTransitionLogCreate) SetStateKey(v string) *StateTransitionLogCreate {
	_c.mutation.SetStateKey(v)
	return _c
}

// SetOldValue sets the "old_value" field.
func (_c *StateTransitionLogCreate) SetOldValue(v string) *StateTransitionLogCreate {
	_c.mutation.SetOldValue(v)
	return _c
}

// SetNillableOldValue sets the "old_value" field if the given value is not nil.
func (_c *StateTransitionLogCreate) SetNillableOldValue(v *string) *StateTransitionLogCreate {
	if v != nil {
		_c.SetOldValue(*v)
	}
	return _c
}

// SetNewValue sets the "new_value" field.
func (_c *StateTransitionLogCreate) SetNewValue(v string) *StateTransitionLogCreate {
	_c.mutation.SetNewValue(v)
	return _c
}

// SetNillableNewValue sets the "new_value" field if the given value is not nil.
func (_c *StateTransitionLogCreate) SetNillableNewValue(v *string) *StateTransitionLogCreate {
	if v != nil {
		_c.SetNewValue(*v)
	}
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *StateTransitionLogCreate) SetTrigger(v string) *StateTransitionLogCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StateTransitionLogCreate) SetCreatedAt(v time.Time) *StateTransitionLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StateTransitionLogCreate) SetNillableCreatedAt(v *time.Time) *StateTransitionLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StateTransitionLogCreate) SetID(v string) *StateTransitionLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the StateTransitionLogMutation object of the builder.
func (_c *StateTransitionLogCreate) Mutation() *StateTransitionLogMutation {
	return _c.mutation
}

// Save creates the StateTransitionLog in the database.
func (_c *StateTransitionLogCreate) Save(ctx context.Context) (*StateTransitionLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StateTransitionLogCreate) SaveX(ctx context.Context) *StateTransitionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StateTransitionLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StateTransitionLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StateTransitionLogCreate) defaults() {
	if _, ok := _c.mutation.OldValue(); !ok {
		v := statetransitionlog.DefaultOldValue
		_c.mutation.SetOldValue(v)
	}
	if _, ok := _c.mutation.NewValue(); !ok {
		v := statetransitionlog.DefaultNewValue
		_c.mutation.SetNewValue(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := statetransitionlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StateTransitionLogCreate) check() error {
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "StateTransitionLog.target"`)}
	}
	if v, ok := _c.mutation.Target(); ok {
		if err := statetransitionlog.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "StateTransitionLog.target": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StateKey(); !ok {
		return &ValidationError{Name: "state_key", err: errors.New(`ent: missing required field "StateTransitionLog.state_key"`)}
	}
	if v, ok := _c.mutation.StateKey(); ok {
		if err := statetransitionlog.StateKeyValidator(v); err != nil {
			return &ValidationError{Name: "state_key", err: fmt.Errorf(`ent: validator failed for field "StateTransitionLog.state_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OldValue(); !ok {
		return &ValidationError{Name: "old_value", err: errors.New(`ent: missing required field "StateTransitionLog.old_value"`)}
	}
	if _, ok := _c.mutation.NewValue(); !ok {
		return &ValidationError{Name: "new_value", err: errors.New(`ent: missing required field "StateTransitionLog.new_value"`)}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "StateTransitionLog.trigger"`)}
	}
	if v, ok := _c.mutation.Trigger(); ok {
		if err := statetransitionlog.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "StateTransitionLog.trigger": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StateTransitionLog.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := statetransitionlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "StateTransitionLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *StateTransitionLogCreate) sqlSave(ctx context.Context) (*StateTransitionLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected StateTransitionLog.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StateTransitionLogCreate) createSpec() (*StateTransitionLog, *sqlgraph.CreateSpec) {
	var (
		_node = &StateTransitionLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(statetransitionlog.Table, sqlgraph.NewFieldSpec(statetransitionlog.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(statetransitionlog.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.StateKey(); ok {
		_spec.SetField(statetransitionlog.FieldStateKey, field.TypeString, value)
		_node.StateKey = value
	}
	if value, ok := _c.mutation.OldValue(); ok {
		_spec.SetField(statetransitionlog.FieldOldValue, field.TypeString, value)
		_node.OldValue = value
	}
	if value, ok := _c.mutation.NewValue(); ok {
		_spec.SetField(statetransitionlog.FieldNewValue, field.TypeString, value)
		_node.NewValue = value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(statetransitionlog.FieldTrigger, field.TypeString, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(statetransitionlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// StateTransitionLogCreateBulk is the builder for creating many StateTransitionLog entities in bulk.
type StateTransitionLogCreateBulk struct {
	config
	err      error
	builders []*StateTransitionLogCreate
}

// Save creates the StateTransitionLog entities in the database.
func (_c *StateTransitionLogCreateBulk) Save(ctx context.Context) ([]*StateTransitionLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StateTransitionLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StateTransitionLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StateTransitionLogCreateBulk) SaveX(ctx context.Context) []*StateTransitionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StateTransitionLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StateTransitionLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
