// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shjtmy/go_sh0jitmy_template/ent/statetransitionlog"
)

// StateTransitionLog is the model entity for the StateTransitionLog schema.
type StateTransitionLog struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Target holds the value of the "target" field.
	Target string `json:"target,omitempty"`
	// StateKey holds the value of the "state_key" field.
	StateKey string `json:"state_key,omitempty"`
	// OldValue holds the value of the "old_value" field.
	OldValue string `json:"old_value,omitempty"`
	// NewValue holds the value of the "new_value" field.
	NewValue string `json:"new_value,omitempty"`
	// Trigger holds the value of the "trigger" field.
	Trigger string `json:"trigger,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StateTransitionLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case statetransitionlog.FieldID, statetransitionlog.FieldTarget, statetransitionlog.FieldStateKey, statetransitionlog.FieldOldValue, statetransitionlog.FieldNewValue, statetransitionlog.FieldTrigger:
			values[i] = new(sql.NullString)
		case statetransitionlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StateTransitionLog fields.
func (_m *StateTransitionLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case statetransitionlog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case statetransitionlog.FieldTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.String
			}
		case statetransitionlog.FieldStateKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state_key", values[i])
			} else if value.Valid {
				_m.StateKey = value.String
			}
		case statetransitionlog.FieldOldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field old_value", values[i])
			} else if value.Valid {
				_m.OldValue = value.String
			}
		case statetransitionlog.FieldNewValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field new_value", values[i])
			} else if value.Valid {
				_m.NewValue = value.String
			}
		case statetransitionlog.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				_m.Trigger = value.String
			}
		case statetransitionlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StateTransitionLog.
// This includes values selected through modifiers, order, etc.
func (_m *StateTransitionLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StateTransitionLog.
// Note that you need to call StateTransitionLog.Unwrap() before calling this method if this StateTransitionLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StateTransitionLog) Update() *StateTransitionLogUpdateOne {
	return NewStateTransitionLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StateTransitionLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StateTransitionLog) Unwrap() *StateTransitionLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StateTransitionLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StateTransitionLog) String() string {
	var builder strings.Builder
	builder.WriteString("StateTransitionLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("target=")
	builder.WriteString(_m.Target)
	builder.WriteString(", ")
	builder.WriteString("state_key=")
	builder.WriteString(_m.StateKey)
	builder.WriteString(", ")
	builder.WriteString("old_value=")
	builder.WriteString(_m.OldValue)
	builder.WriteString(", ")
	builder.WriteString("new_value=")
	builder.WriteString(_m.NewValue)
	builder.WriteString(", ")
	builder.WriteString("trigger=")
	builder.WriteString(_m.Trigger)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StateTransitionLogs is a parsable slice of StateTransitionLog.
type StateTransitionLogs []*StateTransitionLog
